In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('/Users/amroa/Downloads/yelpdata/yelp-csv/yelp_academic_dataset_business.csv')

In [24]:
df

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,postal_code,review_count,stars,state
0,2818 E Camino Acequia Drive,{},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,-112.018481,Arizona Biltmore Golf Club,85016,5,3.0,AZ
1,30 Eglinton Avenue W,"{'GoodForMeal': ""{'dessert': False, 'latenight...",QXAEGFB4oINsVuTFxEYKFQ,"Specialty Food, Restaurants, Dim Sum, Imported...",Mississauga,"{'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W...",1,43.605499,-79.652289,Emerald Chinese Restaurant,L5R 3E7,128,2.5,ON
2,"1210 8th Street SW, Unit 220","{'BusinessParking': ""{'garage': False, 'street...",fcXOEZdXYeZqnQ3lGlOXmg,"Local Services, Professional Services, Compute...",Calgary,"{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...",1,51.041771,-114.081109,Nucleus Information Service,T2R 1L3,5,2.0,AB
3,"6955 N Durango Dr, Ste 1116","{'BusinessParking': ""{'garage': False, 'street...",f2ZWZPENViL92BrFsIgR6w,"Beauty & Spas, Hair Salons",Las Vegas,"{'Monday': '8:30-20:0', 'Tuesday': '8:30-20:0'...",1,36.287312,-115.289540,Amazing Cuts,89149,116,4.5,NV
4,4 E University Dr,{},6KgGE8B1RsR7jc9R5nuH0Q,"American (Traditional), Restaurants",Tempe,NaN,0,33.422192,-111.939615,Ruby Tuesday,85281,9,2.5,AZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192604,521 St. Catherine Street W,"{'Ambience': ""{'romantic': False, 'intimate': ...",wWV90q48ugyxyXW6gZav8w,"Restaurants, Venezuelan, Latin American",Montréal,NaN,0,45.504597,-73.568456,Arepas,H3B 1A6,15,3.5,QC
192605,244 Victoria Street,{},phSaT3I_y6To1J2OdeFSUQ,"Arts & Entertainment, Performing Arts",Toronto,NaN,1,43.655290,-79.379541,Ed Mirvish Theatre,M5B 1V8,58,4.0,ON
192606,10210 South 50th Pl,NaN,oU6Q3ymg1Qsh1EUI6oQwQg,"Education, Middle Schools & High Schools",Phoenix,"{'Monday': '7:30-17:30', 'Tuesday': '7:30-17:3...",1,33.354284,-111.975538,BASIS Ahwatukee,85044,3,2.5,AZ
192607,"6670 S Tenaya Way, Ste 120, The Body Spa","{'BusinessParking': ""{'garage': False, 'street...",gdiOk0n7DmNE9w8xeHWkvw,"Beauty & Spas, Eyelash Service, Waxing, Esthet...",Las Vegas,"{'Monday': '0:0-0:0', 'Tuesday': '9:0-19:0', '...",1,36.066952,-115.251008,Brows Redefined,89113,15,5.0,NV
192608,"14050 N 83rd Ave, Ste 290",NaN,Rv8s4io4G4mcUpiDbpzy7w,"Professional Services, Wills, Trusts, & Probat...",Peoria,"{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",1,33.612226,-112.238145,Affordable Estate Planning,85381,3,5.0,AZ

In [25]:
#obtain a set of all categories

In [26]:
categories = set()
def getAllCategories(categ):
    if (not isinstance(categ, float)):
        categoryList= str(categ).split(', ')
        categories.update(categoryList)
df['categories'].apply(getAllCategories)
# display first few elements
categories

{'British',
 'Auto Customization',
 'Pita',
 'Game Meat',
 'Balloon Services',
 'Colleges & Universities',
 'Backshop',
 'Sugaring',
 'Car Rental',
 'Performing Arts',
 'Digitizing Services',
 'Surgeons',
 'Community Gardens',
 'Hot Tub & Pool',
 'Circuit Training Gyms',
 'Vehicle Shipping',
 'Hydro-jetting',
 'Estate Planning Law',
 'Lawn Services',
 'Otologists',
 'Hang Gliding',
 'Self Storage',
 'Outlet Stores',
 'Television Stations',
 'Feng Shui',
 'Auto Security',
 'Shoe Repair',
 'Cupcakes',
 'Dance Schools',
 'Taxidermy',
 'Sleep Specialists',
 'Hepatologists',
 'Libraries',
 'Vietnamese',
 'Crane Services',
 'Teacher Supplies',
 'Bartending Schools',
 'Battery Stores',
 'Dog Parks',
 'Educational Services',
 'Demolition Services',
 'Wholesale Stores',
 'Pet Waste Removal',
 'Dumpster Rental',
 'Data Recovery',
 'Nail Technicians',
 'Pediatricians',
 'Grilling Equipment',
 'Furniture Repair',
 'Transportation',
 'Bicycles',
 'DUI Schools',
 'CPR Classes',
 'Hainan',
 'Golf Equipment',
 'Social Security Law',
 'Appraisal Services',
 'Internet Service Providers',
 'Embassy',
 'Vegan',
 'Reflexology',
 'Scavenger Hunts',
 'Nurseries & Gardening',
 'Shaved Snow',
 'Used Bookstore',
 'American (New)',
 'Pediatric Dentists',
 'Amateur Sports Teams',
 'Whiskey Bars',
 'Departments of Motor Vehicles',
 'Emergency Pet Hospital',
 'Diving',
 'Health & Medical',
 'Saunas',
 'Cheese Shops',
 'Mortgage Brokers',
 'Scooter Tours',
 'Pressure Washers',
 'Tui Na',
 'Pole Dancing Classes',
 'Water Heater Installation/Repair',
 'Airport Terminals',
 'Henna Artists',
 'Land Surveying',
 'Delis',
 'Doulas',
 'Candle Stores',
 'Singaporean',
 'Patio Coverings',
 'Antiques',
 'Spanish',
 'Watches',
 'Cosmetics & Beauty Supply',
 'Civic Center',
 'Tattoo Removal',
 'Tennis',
 'Hot Dogs',
 'Fish & Chips',
 'Gluten-Free',
 'Austrian',
 'Ice Delivery',
 'Pick Your Own Farms',
 'Czech',
 'Adult Entertainment',
 'Obstetricians & Gynecologists',
 'Midwives',
 'Qi Gong',
 'Train Stations',
 'Colonics',
 'Pain Management',
 'Wedding Chapels',
 'Boxing',
 'Geneticists',
 'Immunodermatologists',
 'Russian',
 'Jet Skis',
 'Paint & Sip',
 'Hair Stylists',
 'Airports',
 'Furniture Reupholstery',
 'Cultural Center',
 'Prenatal/Perinatal Care',
 'Sports Bars',
 'Talent Agencies',
 'Reptile Shops',
 'Ethical Grocery',
 'Animal Assisted Therapy',
 'Professional Sports Teams',
 '& Probates',
 'Limos',
 'Mobile Phone Repair',
 'Pop-Up Restaurants',
 'Patent Law',
 'Video Game Stores',
 'Sporting Goods',
 'Bike Parking',
 'Bed & Breakfast',
 'Tax Law',
 'Pawn Shops',
 'Rugs',
 'Glass Blowing',
 'Appliances',
 'Customized Merchandise',
 'Neurologist',
 'Challenge Courses',
 'Elementary Schools',
 'Campgrounds',
 'Bail Bondsmen',
 'Horseback Riding',
 'Nursing Schools',
 'Couriers & Delivery Services',
 'Car Brokers',
 'Office Cleaning',
 'Personal Assistants',
 'Prosthodontists',
 'Sugar Shacks',
 'Beaches',
 'Pumpkin Patches',
 'Criminal Defense Law',
 'Brasseries',
 'Holistic Animal Care',
 'Bike Sharing',
 'Art Supplies',
 'Water Stores',
 'Cooking Classes',
 'Squash',
 'Ethiopian',
 'Tours',
 'Tea Rooms',
 'Security Services',
 'Interlock Systems',
 'Trampoline Parks',
 'Island Pub',
 'Axe Throwing',
 'Slovakian',
 'Comic Books',
 'Dance Wear',
 'Phlebologists',
 'Masonry/Concrete',
 'Pet Services',
 'Mediators',
 'Free Diving',
 'Beer',
 'Audio/Visual Equipment Rental',
 'Used Car Dealers',
 'Virtual Reality Centers',
 'Public Relations',
 'Payroll Services',
 'Coffeeshops',
 'Skate Shops',
 'Trusts',
 'Oaxacan',
 'Home Staging',
 'Musical Instruments & Teachers',
 'Preschools',
 'Brewpubs',
 'Beer Hall',
 'Bubble Tea',
 'Hakka',
 'Carpenters',
 'Race Tracks',
 'Lingerie',
 'Body Contouring',
 'Appliances & Repair',
 'Restaurant Supplies',
 'Personal Injury Law',
 'Translation Services',
 'Ethnic Grocery',
 'Guest Houses',
 'Yelp Events',
 'Sandblasting',
 'Business Law',
 'Senior Centers',
 'Pest Control',
 'Soup',
 'Comfort Food',
 'Indoor Playcentre',
 'Wigs',
 'Home Inspectors',
 'Home Window Tinting',
 'Gift Shops',
 'RV Parks',
 'Alternative Medicine',
 'Lactation Services',
 'Hats',
 'Commercial Truck Dealers',
 'Osteopaths',
 'Childproofing',
 'Laundry Services',
 'Embroidery & Crochet',
 'Peruvian',
 'Afghan',
 'Dim Sum',
 'Investing',
 'Private Jet Charter',
 'Latin American',
 'Music Production Services',
 'Dietitians',
 'Videos & Video Game Rental',
 'Teeth Whitening',
 'Vegetarian',
 'Casinos',
 'Aquarium Services',
 'Poutineries',
 'Nicaraguan',
 'Synagogues',
 'Amusement Parks',
 'Nanny Services',
 'Military Surplus',
 'Screen Printing',
 'Roadside Assistance',
 'Handyman',
 'Service Stations',
 'Nephrologists',
 'Car Stereo Installation',
 'Tai Chi',
 'Cosmetic Surgeons',
 'Boot Camps',
 'Home Health Care',
 'Tattoo',
 'Walking Tours',
 'Clothing Rental',
 'Driving Schools',
 'Caterers',
 'Engraving',
 'Gerontologists',
 'Professional Services',
 'Popcorn Shops',
 'Horse Equipment Shops',
 'Motorsport Vehicle Dealers',
 'Skin Care',
 'Traffic Schools',
 'Musicians',
 'Pathologists',
 'Travel Services',
 'Fruits & Veggies',
 'IT Services & Computer Repair',
 'Gutter Services',
 'Optometrists',
 'Bookkeepers',
 'Veterinarians',
 'Scottish',
 'Piercing',
 'Auto Glass Services',
 'Permanent Makeup',
 'Beach Volleyball',
 'Outdoor Movies',
 'Packing Services',
 'Internal Medicine',
 'Water Suppliers',
 'Hair Salons',
 'Parking',
 'DJs',
 'Auto Loan Providers',
 'Bird Shops',
 'Hunting & Fishing Supplies',
 'Bridal',
 'Mortuary Services',
 'Car Buyers',
 'Roof Inspectors',
 'Funeral Services & Cemeteries',
 'Gyms',
 'Duty-Free Shops',
 'Laser Tag',
 'Proctologists',
 'Kombucha',
 'Olive Oil',
 'Artificial Turf',
 'Laser Eye Surgery/Lasik',
 'Occupational Therapy',
 'Urologists',
 'Glass & Mirrors',
 'Hot Air Balloons',
 'Concierge Medicine',
 'Montessori Schools',
 'Painters',
 'International',
 'Neuropathologists',
 'Aircraft Repairs',
 'Art Schools',
 'Dermatologists',
 'Thrift Stores',
 'Plus Size Fashion',
 'Donairs',
 'Italian',
 'Waxing',
 'Insulation Installation',
 'Animal Physical Therapy',
 'Floral Designers',
 'Electronics',
 'Periodontists',
 'Guamanian',
 'Hardware Stores',
 'Sailing',
 'Truck Rental',
 'Golf Cart Dealers',
 'Laser Hair Removal',
 'Filipino',
 'Skiing',
 'Udon',
 'Electricity Suppliers',
 'Music Venues',
 'Insurance',
 'Health Insurance Offices',
 'Medical Supplies',
 'Body Shops',
 'Dance Clubs',
 'Japanese Curry',
 'Mailbox Centers',
 'TV Mounting',
 'Rheumatologists',
 'Bike tours',
 'Cryotherapy',
 'Vocal Coach',
 'Gas Stations',
 'Trailer Rental',
 'Assisted Living Facilities',
 'Gunsmith',
 'Jewelry',
 'Radio Stations',
 'Real Estate',
 'Real Estate Agents',
 'Allergists',
 'Bookstores',
 'Barre Classes',
 'Vape Shops',
 'Vacation Rental Agents',
 'Pet Photography',
 'Watch Repair',
 'Cafes',
 'Shared Office Spaces',
 'Pet Sitting',
 'Career Counseling',
 'Dry Cleaning & Laundry',
 'Endocrinologists',
 'African',
 'Supernatural Readings',
 'Guns & Ammo',
 'Creperies',
 'Telecommunications',
 'Art Tours',
 'Diners',
 'Strip Clubs',
 'Skate Parks',
 'Animal Shelters',
 'Lighting Fixtures & Equipment',
 'Wraps',
 'Trophy Shops',
 'Pub Food',
 'Party Characters',
 'Cannabis Collective',
 'Bakeries',
 'Counseling & Mental Health',
 'Food Stands',
 'Attraction Farms',
 'Themed Cafes',
 'Swimming Lessons/Schools',
 'Taekwondo',
 'Arts & Entertainment',
 'Courthouses',
 'Childbirth Education',
 'Health Retreats',
 'Airport Shuttles',
 'Observatories',
 'Hockey Equipment',
 'Food Delivery Services',
 'Bus Tours',
 'Ear Nose & Throat',
 'Zoos',
 'Safety Equipment',
 'Carpet Cleaning',
 'Pet Training',
 'Cocktail Bars',
 'Australian',
 'Tenant and Eviction Law',
 'Reiki',
 'Photographers',
 'Meditation Centers',
 'Sledding',
 'Persian/Iranian',
 'Firewood',
 'Adult',
 'Motorcycle Rental',
 'Fencing Clubs',
 'Halfway Houses',
 'Flight Instruction',
 'Ukrainian',
 'Language Schools',
 'Florists',
 'Indonesian',
 'Paddleboarding',
 'Fireplace Services',
 'Petting Zoos',
 "Children's Museums",
 'Mediterranean',
 'Soccer',
 'Trivia Hosts',
 'Fingerprinting',
 'Hobby Shops',
 'Venezuelan',
 "Children's Clothing",
 'General Festivals',
 'Recreation Centers',
 'Transmission Repair',
 'Aircraft Dealers',
 'Planetarium',
 'Marinas',
 'Furniture Rental',
 'Mattresses',
 'Makeup Artists',
 'Check Cashing/Pay-day Loans',
 'Window Washing',
 'Motorcycle Gear',
 'Rock Climbing',
 'Car Wash',
 'Chocolatiers & Shops',
 'Anesthesiologists',
 'Golf Equipment Shops',
 'Threading Services',
 'Home Services',
 'Team Building Activities',
 'Pakistani',
 'Syrian',
 'Tires',
 'Cafeteria',
 'DUI Law',
 'Gastroenterologist',
 'Opera & Ballet',
 'Active Life',
 'Speech Therapists',
 'First Aid Classes',
 'Mass Media',
 'Street Art',
 'Holiday Decorating Services',
 'Calabrian',
 'Pretzels',
 'Asian Fusion',
 'General Litigation',
 'Fishing',
 'Sandwiches',
 'Propane',
 'Fences & Gates',
 'Organic Stores',
 'Natural Gas Suppliers',
 'Condominiums',
 'Linens',
 'Landmarks & Historical Buildings',
 'Dialysis Clinics',
 'Kitchen Supplies',
 'Blow Dry/Out Services',
 'Face Painting',
 'Bingo Halls',
 'Historical Tours',
 'Brazilian',
 'Wallpapering',
 'Striptease Dancers',
 'Hindu Temples',
 'Dinner Theater',
 'Meat Shops',
 'Steakhouses',
 'Caricatures',
 'Firearm Training',
 'Bangladeshi',
 'Ski Resorts',
 'Beer Garden',
 'Drugstores',
 'Wine & Spirits',
 'Office Equipment',
 'Grocery',
 'Interior Design',
 'Garage Door Services',
 'Bar Crawl',
 'Iberian',
 'Psychic Mediums',
 'Auto Detailing',
 'Prosthetics',
 'Rolfing',
 'Private Schools',
 'Supper Clubs',
 'Home Theatre Installation',
 'Juice Bars & Smoothies',
 'RV Dealers',
 'Do-It-Yourself Food',
 'Tempura',
 'Dance Studios',
 'Well Drilling',
 'Taiwanese',
 'Naturopathic/Holistic',
 'Radiologists',
 'Medical Spas',
 'Bocce Ball',
 'Christmas Trees',
 'Party Bus Rentals',
 'Cosmetic Dentists',
 'Haunted Houses',
 'Local Fish Stores',
 'Title Loans',
 'Car Dealers',
 'Club Crawl',
 'Playgrounds',
 'Television Service Providers',
 'Imported Food',
 'Lounges',
 'Lice Services',
 'Solar Panel Cleaning',
 'Editorial Services',
 'Distilleries',
 'Surf Schools',
 'Gelato',
 'Herbs & Spices',
 'Bespoke Clothing',
 'Auction Houses',
 'Batting Cages',
 'Trains',
 'Advertising',
 'Installment Loans',
 'Pet Groomers',
 'College Counseling',
 'Health Markets',
 'House Sitters',
 'Brewing Supplies',
 'Life Insurance',
 'Leather Goods',
 'Honey',
 'Festivals',
 'Trailer Dealers',
 'Cantonese',
 'Siding',
 'Senegalese',
 'Gastropubs',
 'Hotels',
 'Pool & Billiards',
 'Irrigation',
 'Gymnastics',
 'Beauty & Spas',
 'Disability Law',
 'Minho',
 'Vascular Medicine',
 'Luggage',
 'Waffles',
 'Irish Pub',
 'Massage Therapy',
 'Mobile Dent Repair',
 'Props',
 'Soul Food',
 'Used',
 'Video/Film Production',
 'Estheticians',
 'Beach Equipment Rentals',
 'Pop-up Shops',
 'Pasta Shops',
 'Surf Shop',
 'Sport Equipment Hire',
 'Town Car Service',
 'Motorcycle Repair',
 'Karaoke',
 'Passport & Visa Services',
 'Portuguese',
 'Property Management',
 'Greek',
 'Piano Bars',
 'Graphic Design',
 'Buses',
 'Electricians',
 'Home Network Installation',
 'Argentine',
 'Divorce & Family Law',
 'Hospice',
 'Oil Change Stations',
 'Visitor Centers',
 'Decks & Railing',
 'Concept Shops',
 'Music & Video',
 'Indoor Landscaping',
 'Recycling Center',
 'Tanning Beds',
 'Religious Organizations',
 'Employment Agencies',
 'Personal Shopping',
 'Hair Extensions',
 'Tickets',
 'Desserts',
 'Tiling',
 'Comedy Clubs',
 'Salad',
 'Moroccan',
 'Seafood',
 'Real Estate Photography',
 'Travel Agents',
 'Basketball Courts',
 'Food Tours',
 'Hookah Bars',
 'Diagnostic Imaging',
 'Officiants',
 'Financial Services',
 'Hair Removal',
 'Diagnostic Services',
 'Memory Care',
 'Department Stores',
 'Herbal Shops',
 'Macarons',
 'Pan Asian',
 'Beer Bar',
 'Ethnic Food',
 'Mini Golf',
 'Party Supplies',
 'Motorcycle Dealers',
 'Walk-in Clinics',
 'Employment Law',
 'Swimwear',
 'Event Planning & Services',
 'Barbers',
 'Veterans Organizations',
 'Escape Games',
 'Tableware',
 'Workers Compensation Law',
 'Session Photography',
 'Milkshake Bars',
 'Art Museums',
 'Environmental Testing',
 'Chiropractors',
 'Scandinavian',
 'Nail Salons',
 'Social Clubs',
 'Endodontists',
 'Hair Loss Centers',
 'Legal Services',
 'Pets',
 'Fuel Docks',
 'Swimming Pools',
 'Donuts',
 'Door Sales/Installation',
 'Game Truck Rental',
 'Mobile Phones',
 'Medical Centers',
 'Burmese',
 'Churros',
 'Clock Repair',
 'Rafting/Kayaking',
 'Drive-In Theater',
 'Lakes',
 'Towing',
 'Badminton',
 'Coffee Roasteries',
 'Baseball Fields',
 'Ticket Sales',
 'Kiosk',
 'Windows Installation',
 'Water Delivery',
 'Beer Gardens',
 'Plastic Surgeons',
 'Apartments',
 'Furniture Assembly',
 'Japanese Sweets',
 'RV Rental',
 'Security Systems',
 'Teppanyaki',
 'Hawaiian',
 'Cambodian',
 'Special Education',
 'Photography Classes',
 'Pet Transportation',
 'Chinese',
 'Outdoor Furniture Stores',
 'Cinema',
 'Public Transportation',
 'Spray Tanning',
 'Food',
 'Electronics Repair',
 'Valet Services',
 'Wills',
 'Holiday Decorations',
 'Photography Stores & Services',
 'Auto Upholstery',
 'Shaved Ice',
 'Nightlife',
 'Motorsport Vehicle Repairs',
 'Carpet Installation',
 "Men's Hair Salons",
 'Sports Clubs',
 'Sports Psychologists',
 'Shoe Shine',
 'Japanese',
 'IV Hydration',
 'Street Vendors',
 'Aquariums',
 'Golf',
 'Traditional Chinese Medicine',
 'Beverage Store',
 'Notaries',
 'Racing Experience',
 'Retirement Homes',
 'Pet Breeders',
 'Fondue',
 'Head Shops',
 'French',
 'Karate',
 'Rodeo',
 'Building Supplies',
 'Placenta Encapsulations',
 'Public Adjusters',
 'Internet Cafes',
 'Airport Lounges',
 'Auto Insurance',
 'Addiction Medicine',
 'Farms',
 'Packing Supplies',
 'Immigration Law',
 'Emergency Rooms',
 'Automotive',
 'Undersea/Hyperbaric Medicine',
 'Himalayan/Nepalese',
 'Bulgarian',
 'Water Purification Services',
 'Drones',
 'Musical Instrument Services',
 'Farmers Market',
 'Boat Parts & Supplies',
 'Shredding Services',
 'Beach Bars',
 'Vehicle Wraps',
 'Hypnosis/Hypnotherapy',
 'South African',
 'Printing Services',
 'Fireworks',
 'Bikes',
 'Live/Raw Food',
 'Scooter Rentals',
 'Chicken Wings',
 'Egyptian',
 'Spine Surgeons',
 'Urgent Care',
 'Cheesesteaks',
 'Archery',
 'Szechuan',
 'Laundromat',
 'Junk Removal & Hauling',
 'Discount Store',
 'Tonkatsu',
 'Tasting Classes',
 'Gun/Rifle Ranges',
 'Pet Cremation Services',
 'Matchmakers',
 'Pedicabs',
 'Chimney Sweeps',
 "Women's Clothing",
 'Cremation Services',
 'Contractors',
 'Mountain Biking',
 'Hearing Aids',
 'Car Inspectors',
 'Ophthalmologists',
 'Kosher',
 'Framing',
 'Coffee & Tea Supplies',
 'Health Coach',
 'Real Estate Law',
 'Kids Activities',
 'Flooring',
 'Acai Bowls',
 'Car Share Services',
 'Carpet Dyeing',
 'Hearing Aid Providers',
 'Laboratory Testing',
 'Physical Therapy',
 'Ramen',
 'Knife Sharpening',
 'Tapas Bars',
 'Country Clubs',
 'Traditional Clothing',
 'Museums',
 'Shopping',
 'Luggage Storage',
 'Kids Hair Salons',
 'Food Banks',
 'Homeowner Association',
 'Horse Boarding',
 'Patisserie/Cake Shop',
 'Indian',
 'Storefront Clinics',
 'Foundation Repair',
 'Butcher',
 'Psychics',
 'Smog Check Stations',
 'Mauritius',
 'Family Practice',
 'Drywall Installation & Repair',
 'Education',
 'Fabric Stores',
 'Acne Treatment',
 'Bartenders',
 'Fertility',
 'Sri Lankan',
 'General Dentistry',
 'Machine & Tool Rental',
 'Backflow Services',
 'Print Media',
 'Mobility Equipment Sales & Services',
 'Life Coach',
 'Bagels',
 'Baby Gear & Furniture',
 'Day Spas',
 'Signmaking',
 'Home Cleaning',
 'Formal Wear',
 'Makerspaces',
 'Local Flavor',
 'Bars',
 'Estate Liquidation',
 'Tanning',
 'Commercial Real Estate',
 'Hostels',
 'Muay Thai',
 'Costumes',
 'Preventive Medicine',
 'Breweries',
 'Snow Removal',
 'Skydiving',
 'Debt Relief Services',
 'Erotic Massage',
 'Adult Education',
 'Shades & Blinds',
 'Nurse Practitioner',
 'Psychiatrists',
 'Carousels',
 'Massage',
 'Go Karts',
 'Wedding Planning',
 'Traffic Ticketing Law',
 'Books',
 'Outdoor Gear',
 'Grout Services',
 'Kitchen & Bath',
 'Contract Law',
 'Home & Garden',
 'Haitian',
 'IP & Internet Law',
 'ATV Rentals/Tours',
 'Auto Repair',
 'Financial Advising',
 'Astrologers',
 'Shoe Stores',
 "Men's Clothing",
 '3D Printing',
 'Buffets',
 'Parenting Classes',
 'Arabian',
 'Home Energy Auditors',
 'Aerial Tours',
 'Caribbean',
 'Bus Rental',
 'Dental Hygienists',
 'Mosques',
 'Guitar Stores',
 'Home & Rental Insurance',
 'Ice Cream & Frozen Yogurt',
 'Bankruptcy Law',
 'Pool Halls',
 'Parks',
 'Beer Tours',
 'Donation Center',
 'Oral Surgeons',
 'Flea Markets',
 'Swiss Food',
 'Misting System Services',
 'Hong Kong Style Cafe',
 'Medical Transportation',
 'Auto Electric Services',
 'Halotherapy',
 'Commissioned Artists',
 'Event Photography',
 'Rehabilitation Center',
 'Sushi Bars',
 'Plumbing',
 'Laotian',
 'Pet Hospice',
 'Christmas Markets',
 'Experiences',
 'Float Spa',
 'Ceremonial Clothing',
 'Noodles',
 'Oxygen Bars',
 'Izakaya',
 'Court Reporters',
 'Playsets',
 'Tree Services',
 'Solar Installation',
 'Leisure Centers',
 'Sewing & Alterations',
 'Cardio Classes',
 'Town Hall',
 'Windshield Installation & Repair',
 'Safe Stores',
 'Calligraphy',
 'Refinishing Services',
 'Magicians',
 'Fire Protection Services',
 'CSA',
 'Barbeque',
 'Champagne Bars',
 'Art Classes',
 'Ski & Snowboard Shops',
 'Bookbinding',
 'Mobile Phone Accessories',
 'Cards & Stationery',
 'Dive Shops',
 'Nudist',
 'Videographers',
 'Disc Golf',
 'Stucco Services',
 'Modern European',
 'Pharmacy',
 'Nutritionists',
 'Home Decor',
 'Septic Services',
 'Wine Tours',
 'Doctors',
 'Pizza',
 'Summer Camps',
 'Metro Stations',
 'Yoga',
 'Sunglasses',
 'Junkyards',
 'Dog Walkers',
 'Vinyl Records',
 'Surfing',
 'Furniture Stores',
 'Business Consulting',
 'Drive-Thru Bars',
 'Metal Fabricators',
 'Trailer Repair',
 'Eatertainment',
 'Shopping Centers',
 'Boat Dealers',
 'Mortgage Lenders',
 'Fitness/Exercise Equipment',
 'Cabinetry',
 'Middle Schools & High Schools',
 'Duplication Services',
 'Empanadas',
 'Hiking',
 'Movers',
 'Customs Brokers',
 'Lighting Stores',
 'Mobile Home Dealers',
 'EV Charging Stations',
 'Adoption Services',
 'Cardiologists',
 'Cajun/Creole',
 'Poke',
 'Bowling',
 'Jails & Prisons',
 'Bistros',
 'Wholesalers',
 'Medical Cannabis Referrals',
 'Ski Schools',
 'Races & Competitions',
 'Osteopathic Physicians',
 'Boudoir Photography',
 'Behavior Analysts',
 ...}

In [27]:
# In this step, loop over the set and filter the df by those businesses that contain that category label
len(categories)

1300

In [28]:
hasCategory = {'business_id':[], 'businessLabel':[]}
df3 = pd.DataFrame(hasCategory)

In [29]:
# fucking filtering is too slow (pandas is fast --big fucking lol)
# see the two cells after thus one for how to do it in decent time
#for label in categories:
#    filt = (df['categories'].str.contains(label, na=False))
#    for business in df.loc[filt, 'business_id']:
#        df3 = df3.append({'business_id':business, 'businessLabel':label}, ignore_index = True)
#print('done')

In [30]:
#expect 30 seconds for this shit to finish
import pandas as pd
df = pd.read_csv("/Users/amroa/Downloads/yelpdata/yelp-csv/yelp_academic_dataset_business.csv")

df_categories = df[['business_id', 'categories']]

business_id_labels = list() 
business_id_done = set() 


for i in df_categories.index: 
    business_id = df_categories.loc[i, 'business_id']
    categ_string = df_categories.loc[i, 'categories']
    if(str(categ_string) != "nan"): 
        categ_list = categ_string.split(', ')
        if not ( business_id in business_id_done) : 
            business_id_done.add(business_id)
            business_id_labels.extend(list(map(lambda label : (business_id, label) ,categ_list)))
            

business_id_labels_df = pd.DataFrame(business_id_labels, columns = ['business_id', 'businessLabel'])
business_id_labels_df.to_csv("business_id_categories.csv", index = False)
print('done')

done

In [31]:
# now get the fucking labels themselves
business_id_labels_df

                   business_id        businessLabel
0       1SWheh84yJXfytovILXOAQ                 Golf
1       1SWheh84yJXfytovILXOAQ          Active Life
2       QXAEGFB4oINsVuTFxEYKFQ       Specialty Food
3       QXAEGFB4oINsVuTFxEYKFQ          Restaurants
4       QXAEGFB4oINsVuTFxEYKFQ              Dim Sum
...                        ...                  ...
788354  Rv8s4io4G4mcUpiDbpzy7w               Trusts
788355  Rv8s4io4G4mcUpiDbpzy7w           & Probates
788356  Rv8s4io4G4mcUpiDbpzy7w              Lawyers
788357  Rv8s4io4G4mcUpiDbpzy7w       Legal Services
788358  Rv8s4io4G4mcUpiDbpzy7w  Estate Planning Law

[788359 rows x 2 columns]

In [32]:
# save the fucking categories
labels = business_id_labels_df['businessLabel']
labelsdf = pd.DataFrame(labels, columns = ['businessLabel'])
labelsdf.drop_duplicates(subset ="businessLabel", 
                     keep = 'first', inplace = True) 
labelsdf.to_csv("category_labels.csv", index = False)
labelsdf

            businessLabel
0                    Golf
1             Active Life
2          Specialty Food
3             Restaurants
4                 Dim Sum
...                   ...
699129         Island Pub
717899        Homeopathic
721641  Medical Foot Care
729211        Geneticists
730657        Calligraphy

[1300 rows x 1 columns]

In [33]:
# now the fucking elite
df_users = pd.read_csv('/Users/amroa/Downloads/yelpdata/yelp-csv/yelp_academic_dataset_user.csv')
df_elite = pd.DataFrame(df_users[['user_id','elite']], columns = ['user_id', 'elite'])
df_elite = df_elite.dropna()

In [34]:
df_elite

                       user_id                                    elite
0       l6BmjZMeQD3rDxWUbiAiow                           2015,2016,2017
4       MM4RJAeH6yuaN8oZDSt0RA                      2015,2016,2017,2018
5       0rK89TS8xqy1wI4nYI1wfw                      2015,2016,2017,2018
6       TEtzbpgA2BFBrC0y0sCbfw  2006,2007,2008,2009,2010,2011,2012,2013
8       T0gWkTHWRChVUe_Dn1F8nw       2006,2007,2008,2009,2010,2011,2012
...                        ...                                      ...
778085  lLevwsNW8gyvBRRY5WFSgg                                     2018
778225  TvKpazAvQLSnKwodcuuEYg                                     2018
778471  xJEbA3Dwldz_twXsHNaJhA                                     2018
778589  mSaD4g37jCy4-95pB6NWKA                                     2018
778643  7kACk6ZydEKDwJ7tz5r1pw                                     2018

[70559 rows x 2 columns]

In [35]:
df_elite['elite'].str.split(',', expand = True)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2015,2016,2017,None,None,None,None,None,None,None,None,None,None
4,2015,2016,2017,2018,None,None,None,None,None,None,None,None,None
5,2015,2016,2017,2018,None,None,None,None,None,None,None,None,None
6,2006,2007,2008,2009,2010,2011,2012,2013,None,None,None,None,None
8,2006,2007,2008,2009,2010,2011,2012,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
778085,2018,None,None,None,None,None,None,None,None,None,None,None,None
778225,2018,None,None,None,None,None,None,None,None,None,None,None,None
778471,2018,None,None,None,None,None,None,None,None,None,None,None,None
778589,2018,None,None,None,None,None,None,None,None,None,None,None,None
778643,2018,None,None,None,None,None,None,None,None,None,None,None,None

In [36]:
yearset = set()
def getAllYears(years):
    if (not isinstance(years, float)):
        yrlist = str(years).split(',')
        yearset.update(yrlist)
df_elite['elite'].apply(getAllYears)
# display all the years of eliteshitmanship
yearset

{'2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018'}

In [37]:
# note to self: only call dataframe.append in a loop when you want to kill yourself
list_user_year = list()
for index, row in df_elite.iterrows():
    listyrs = row['elite'].split(',')
    list_user_year.extend(list(map(lambda label : (row['user_id'], label) ,listyrs)))
df_iselite = pd.DataFrame(list_user_year, columns = ['user_id', 'elite_year'])
print('done')

done

In [38]:
df_iselite.to_csv('isElite.csv', index = False)
df_iselite

                       user_id elite_year
0       l6BmjZMeQD3rDxWUbiAiow       2015
1       l6BmjZMeQD3rDxWUbiAiow       2016
2       l6BmjZMeQD3rDxWUbiAiow       2017
3       MM4RJAeH6yuaN8oZDSt0RA       2015
4       MM4RJAeH6yuaN8oZDSt0RA       2016
...                        ...        ...
223172  lLevwsNW8gyvBRRY5WFSgg       2018
223173  TvKpazAvQLSnKwodcuuEYg       2018
223174  xJEbA3Dwldz_twXsHNaJhA       2018
223175  mSaD4g37jCy4-95pB6NWKA       2018
223176  7kACk6ZydEKDwJ7tz5r1pw       2018

[223177 rows x 2 columns]

In [39]:
df_elite_years = pd.DataFrame(yearset, columns = ['elite_year'])
df_elite_years.to_csv('elite.csv', index=False)
df_elite_years

   elite_year
0        2006
1        2012
2        2015
3        2008
4        2007
5        2014
6        2010
7        2018
8        2011
9        2009
10       2016
11       2017
12       2013