In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('yelpdata/yelp-csv/yelp_academic_dataset_business.csv')

In [15]:
df

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,postal_code,review_count,stars,state
0,2818 E Camino Acequia Drive,{},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,-112.018481,Arizona Biltmore Golf Club,85016,5,3.0,AZ
1,30 Eglinton Avenue W,"{'GoodForMeal': ""{'dessert': False, 'latenight...",QXAEGFB4oINsVuTFxEYKFQ,"Specialty Food, Restaurants, Dim Sum, Imported...",Mississauga,"{'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W...",1,43.605499,-79.652289,Emerald Chinese Restaurant,L5R 3E7,128,2.5,ON
2,"1210 8th Street SW, Unit 220","{'BusinessParking': ""{'garage': False, 'street...",fcXOEZdXYeZqnQ3lGlOXmg,"Local Services, Professional Services, Compute...",Calgary,"{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...",1,51.041771,-114.081109,Nucleus Information Service,T2R 1L3,5,2.0,AB
3,"6955 N Durango Dr, Ste 1116","{'BusinessParking': ""{'garage': False, 'street...",f2ZWZPENViL92BrFsIgR6w,"Beauty & Spas, Hair Salons",Las Vegas,"{'Monday': '8:30-20:0', 'Tuesday': '8:30-20:0'...",1,36.287312,-115.289540,Amazing Cuts,89149,116,4.5,NV
4,4 E University Dr,{},6KgGE8B1RsR7jc9R5nuH0Q,"American (Traditional), Restaurants",Tempe,NaN,0,33.422192,-111.939615,Ruby Tuesday,85281,9,2.5,AZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192604,521 St. Catherine Street W,"{'Ambience': ""{'romantic': False, 'intimate': ...",wWV90q48ugyxyXW6gZav8w,"Restaurants, Venezuelan, Latin American",Montréal,NaN,0,45.504597,-73.568456,Arepas,H3B 1A6,15,3.5,QC
192605,244 Victoria Street,{},phSaT3I_y6To1J2OdeFSUQ,"Arts & Entertainment, Performing Arts",Toronto,NaN,1,43.655290,-79.379541,Ed Mirvish Theatre,M5B 1V8,58,4.0,ON
192606,10210 South 50th Pl,NaN,oU6Q3ymg1Qsh1EUI6oQwQg,"Education, Middle Schools & High Schools",Phoenix,"{'Monday': '7:30-17:30', 'Tuesday': '7:30-17:3...",1,33.354284,-111.975538,BASIS Ahwatukee,85044,3,2.5,AZ
192607,"6670 S Tenaya Way, Ste 120, The Body Spa","{'BusinessParking': ""{'garage': False, 'street...",gdiOk0n7DmNE9w8xeHWkvw,"Beauty & Spas, Eyelash Service, Waxing, Esthet...",Las Vegas,"{'Monday': '0:0-0:0', 'Tuesday': '9:0-19:0', '...",1,36.066952,-115.251008,Brows Redefined,89113,15,5.0,NV
192608,"14050 N 83rd Ave, Ste 290",NaN,Rv8s4io4G4mcUpiDbpzy7w,"Professional Services, Wills, Trusts, & Probat...",Peoria,"{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",1,33.612226,-112.238145,Affordable Estate Planning,85381,3,5.0,AZ

In [16]:
#obtain a set of all categories

In [17]:
categories = set()
def getAllCategories(categ):
    if (not isinstance(categ, float)):
        categoryList= str(categ).split(', ')
        categories.update(categoryList)
df['categories'].apply(getAllCategories)
# display first few elements
categories

{'Bus Tours',
 'Obstetricians & Gynecologists',
 'Racing Experience',
 'Piercing',
 'Outdoor Gear',
 'Skin Care',
 'Infectious Disease Specialists',
 'Ophthalmologists',
 'Threading Services',
 'Ayurveda',
 'Sushi Bars',
 'Arabian',
 'Macarons',
 'Middle Eastern',
 'Reunion',
 'Used Bookstore',
 'Beer Hall',
 'Motorsport Vehicle Repairs',
 'Churches',
 'Buddhist Temples',
 'Virtual Reality Centers',
 'Himalayan/Nepalese',
 'Trailer Dealers',
 'Argentine',
 'Storefront Clinics',
 'Clowns',
 'Performing Arts',
 'Beach Equipment Rentals',
 'Barbeque',
 'Go Karts',
 'Hang Gliding',
 'Health Retreats',
 'Comic Books',
 'Cantonese',
 'Swimming Pools',
 'Pedicabs',
 'Trivia Hosts',
 'Hearing Aids',
 'Ranches',
 'Urgent Care',
 'Ticket Sales',
 'American (Traditional)',
 'Sporting Goods',
 'Immigration Law',
 'Medical Cannabis Referrals',
 'Korean',
 'Formal Wear',
 'Customized Merchandise',
 'Cabaret',
 'Notaries',
 'Outlet Stores',
 'Bulgarian',
 'Cardiologists',
 'Security Services',
 'Fitness/Exercise Equipment',
 'Hunting & Fishing Supplies',
 'Sauna Installation & Repair',
 'Animal Assisted Therapy',
 'Delis',
 'Pet Cremation Services',
 'Dive Shops',
 'Pet Groomers',
 'Czech/Slovakian',
 'Elder Care Planning',
 'Peruvian',
 'Supper Clubs',
 'Hobby Shops',
 'Thrift Stores',
 'Float Spa',
 'Foundation Repair',
 'Cigar Bars',
 'Resorts',
 'Junk Removal & Hauling',
 'Steakhouses',
 'Car Share Services',
 'Video/Film Production',
 'Leisure Centers',
 'Natural Gas Suppliers',
 'Waffles',
 'Carpenters',
 'Pet Services',
 'Workers Compensation Law',
 'Neurologist',
 'Permanent Makeup',
 'Medical Law',
 'Auto Electric Services',
 'Street Art',
 'Editorial Services',
 'Dog Walkers',
 'Drywall Installation & Repair',
 'Sports Psychologists',
 'Nephrologists',
 'Hats',
 'Concept Shops',
 'Vacation Rental Agents',
 'Unofficial Yelp Events',
 'Jet Skis',
 'Wine & Spirits',
 'Cycling Classes',
 'Legal Services',
 'Furniture Assembly',
 'Flyboarding',
 'Windows Installation',
 'Dim Sum',
 'Aquariums',
 'Laser Eye Surgery/Lasik',
 'Registration Services',
 'Gay Bars',
 'Art Galleries',
 'Holiday Decorating Services',
 'Banks & Credit Unions',
 'Breweries',
 'Shipping Centers',
 'University Housing',
 'Hair Extensions',
 'Lingerie',
 'Nightlife',
 'French',
 'Gluten-Free',
 'Casinos',
 'Cajun/Creole',
 'Session Photography',
 'Travel Agents',
 'Cosmetic Surgeons',
 'Tanning',
 'Pathologists',
 'Cupcakes',
 'Artificial Turf',
 'Home Window Tinting',
 'Watch Repair',
 'Tempura',
 'Used',
 'Surf Shop',
 'Izakaya',
 'Chinese',
 'Sewing & Alterations',
 'Carousels',
 'Ramen',
 'Limos',
 'Bingo Halls',
 'Mobile Phones',
 'Nursing Schools',
 'Duplication Services',
 'Noodles',
 'Water Stores',
 'Chiropractors',
 'Gardeners',
 'Lighting Stores',
 'Windshield Installation & Repair',
 'Mexican',
 'Champagne Bars',
 'Sleep Specialists',
 'Dry Cleaning',
 'Skate Parks',
 'Neuropathologists',
 'Airports',
 'Montessori Schools',
 'Wine Tasting Room',
 'Auto Repair',
 'Elementary Schools',
 'Entertainment Law',
 'Imported Food',
 'Challenge Courses',
 'Town Car Service',
 'Bike tours',
 'Paint Stores',
 'Day Camps',
 'Home Theatre Installation',
 'Tattoo',
 'Laser Hair Removal',
 'Septic Services',
 'Refinishing Services',
 'Bike Repair/Maintenance',
 'Scuba Diving',
 'Education',
 'Pet Breeders',
 'Nail Technicians',
 'Gift Shops',
 'Coffee Roasteries',
 'Couriers & Delivery Services',
 'Tasting Classes',
 'Recording & Rehearsal Studios',
 'Orthodontists',
 'Guest Houses',
 'Game Truck Rental',
 'Immunodermatologists',
 'Chicken Wings',
 'Indian',
 'Sports Medicine',
 'Magicians',
 'Arcades',
 'Pool & Hot Tub Service',
 'Gemstones & Minerals',
 'Ethnic Food',
 'Knitting Supplies',
 'Races & Competitions',
 'Home & Rental Insurance',
 'Bakeries',
 'Life Insurance',
 'Smokehouse',
 'Car Stereo Installation',
 'Snow Removal',
 'Greek',
 'Acne Treatment',
 'Art Museums',
 'American (New)',
 'Land Surveying',
 'Bridal',
 'Excavation Services',
 'Plastic Surgeons',
 'Hakka',
 'Food Trucks',
 'Bespoke Clothing',
 'Custom Cakes',
 'Allergists',
 'Kitchen & Bath',
 'Experiences',
 'Thai',
 'Boat Dealers',
 'Hockey Equipment',
 'Lakes',
 'Axe Throwing',
 'Insurance',
 'Makerspaces',
 'Car Window Tinting',
 'Massage Schools',
 'Party Bus Rentals',
 'Urologists',
 'Horse Racing',
 'Czech',
 'Real Estate Photography',
 'Skilled Nursing',
 'Mattresses',
 'Tax Services',
 'Ice Cream & Frozen Yogurt',
 'Mobile Phone Repair',
 'Middle Schools & High Schools',
 'Health & Medical',
 'Ceremonial Clothing',
 'Soccer',
 'Municipality',
 'Aviation Services',
 'Packing Supplies',
 'Radiologists',
 'Otologists',
 'Hindu Temples',
 'Bikes',
 'Holiday Decorations',
 'Surf Schools',
 'Fashion',
 'Beer Gardens',
 'Spray Tanning',
 'Cannabis Collective',
 'Shades & Blinds',
 'Parking',
 'Golf',
 'Cheerleading',
 'African',
 'Donairs',
 'Shoe Stores',
 'Structural Engineers',
 'Advertising',
 'Home Developers',
 'Kombucha',
 'Auto Upholstery',
 'Cannabis Tours',
 'Behavior Analysts',
 'Crane Services',
 'Awnings',
 'Opera & Ballet',
 'Private Investigation',
 'Sicilian',
 'Mobile Home Repair',
 'Electronics',
 'Property Management',
 'General Dentistry',
 'Funeral Services & Cemeteries',
 'Specialty Food',
 'Financial Services',
 'Pasta Shops',
 'Real Estate Agents',
 'Installment Loans',
 'Financial Advising',
 'Web Design',
 'Used Car Dealers',
 'Emergency Medicine',
 'Airport Shuttles',
 'Pan Asian',
 'Cideries',
 'Mass Media',
 'Transmission Repair',
 'Trusts',
 'Military Surplus',
 'Caricatures',
 'Knife Sharpening',
 'Reptile Shops',
 'Plumbing',
 'Brasseries',
 'Coffeeshops',
 'Dietitians',
 'Flowers',
 'Cuban',
 'Self Storage',
 'Machine & Tool Rental',
 'Memory Care',
 'Nurse Practitioner',
 'Adult Education',
 'Pet Insurance',
 'Southern',
 'Sex Therapists',
 'Grout Services',
 'Car Inspectors',
 'Acupuncture',
 'Fur Clothing',
 'Fingerprinting',
 'Air Duct Cleaning',
 'Health Markets',
 'Television Stations',
 'Home Services',
 'Diagnostic Imaging',
 'Scooter Tours',
 'Rock Climbing',
 'Hungarian',
 'Egyptian',
 'Golf Cart Dealers',
 'Environmental Testing',
 'Fireworks',
 'Eatertainment',
 'Printing Services',
 'Herbs & Spices',
 'Real Estate',
 'Car Wash',
 'Internet Cafes',
 'Hazardous Waste Disposal',
 'Fencing Clubs',
 'Train Stations',
 'Doctors',
 'Pool & Billiards',
 'Habilitative Services',
 'Patio Coverings',
 'Mobile Home Parks',
 'Body Contouring',
 'Cannabis Dispensaries',
 'Commercial Truck Repair',
 'Oxygen Bars',
 'Tapas Bars',
 'Water Heater Installation/Repair',
 'Luggage Storage',
 'Party Equipment Rentals',
 'Vehicle Wraps',
 'Wildlife Control',
 'Beverage Store',
 'Gymnastics',
 'Office Cleaning',
 'Private Tutors',
 'Poke',
 'Family Practice',
 'Karate',
 'Pet Hospice',
 'Department Stores',
 'Police Departments',
 'Airport Lounges',
 'Interval Training Gyms',
 'Hookah Bars',
 'Game Meat',
 'Employment Agencies',
 'Churros',
 'Radio Stations',
 'Buses',
 'Mediterranean',
 'Perfume',
 'Circuit Training Gyms',
 'Kids Hair Salons',
 'Rugs',
 'Maternity Wear',
 'Career Counseling',
 'Cosmetics & Beauty Supply',
 'Day Spas',
 'Singaporean',
 'Dance Studios',
 'Solar Panel Cleaning',
 'Piano Stores',
 'Cosmetic Dentists',
 'Tours',
 'Cannabis Clinics',
 'Auto Detailing',
 'Carpet Dyeing',
 'Gunsmith',
 'Scavenger Hunts',
 'Skiing',
 'Shopping',
 'Translation Services',
 'Kosher',
 'Jewelry Repair',
 'Butcher',
 'Waterproofing',
 'Coffee & Tea',
 'Bangladeshi',
 'Vocational & Technical School',
 'Auto Loan Providers',
 'Museums',
 'Public Markets',
 'Tacos',
 'Grocery',
 'Pool Cleaners',
 'Hot Air Balloons',
 'Lice Services',
 'Transportation',
 'Framing',
 'Qi Gong',
 'Piano Services',
 'House Sitters',
 'Seafood Markets',
 'Bankruptcy Law',
 'Tax Law',
 'Fishing',
 'Cosmetology Schools',
 'Burgers',
 'Archery',
 'Painters',
 'Empanadas',
 'Distilleries',
 'Mediators',
 'Mountain Biking',
 'Medical Transportation',
 'Sugaring',
 'Lactation Services',
 'Mauritius',
 'Rest Stops',
 'Dentists',
 'Disability Law',
 'Process Servers',
 'Spin Classes',
 'Employment Law',
 'Pick Your Own Farms',
 'Personal Assistants',
 'Auto Customization',
 'Olive Oil',
 'Boot Camps',
 'Beer Bar',
 'Carpet Cleaning',
 'Food Banks',
 'Shoe Repair',
 'Belgian',
 'Psychic Mediums',
 'Business Consulting',
 'Trains',
 'Cardio Classes',
 'Trophy Shops',
 'Fast Food',
 'Public Adjusters',
 'Estate Planning Law',
 'Glass Blowing',
 'Body Shops',
 'Hair Loss Centers',
 'Metro Stations',
 'Creperies',
 'Social Clubs',
 'New Mexican Cuisine',
 'Local Fish Stores',
 'Patent Law',
 'Ear Nose & Throat',
 'Weight Loss Centers',
 'Naturopathic/Holistic',
 'Dinner Theater',
 'Astrologers',
 'Organic Stores',
 'Dog Parks',
 'Religious Schools',
 'Cabinetry',
 'Audiologist',
 'Automotive',
 'Arts & Entertainment',
 'Truck Rental',
 'RV Parks',
 'Scooter Rentals',
 'IP & Internet Law',
 'RV Dealers',
 'Preventive Medicine',
 'Language Schools',
 'Home Cleaning',
 'Chicken Shop',
 'Livestock Feed & Supply',
 'Golf Equipment',
 'Pest Control',
 'Ice Delivery',
 'Food',
 'Comedy Clubs',
 'International Grocery',
 'Home Health Care',
 'Architectural Tours',
 'Irish Pub',
 'Handyman',
 'Do-It-Yourself Food',
 'Sunglasses',
 'Business Financing',
 'Skating Rinks',
 'Retirement Homes',
 'Hepatologists',
 'Educational Services',
 'Hair Stylists',
 'Taxis',
 'Pole Dancing Classes',
 'Salvadoran',
 'Sandblasting',
 'Car Rental',
 'Cafeteria',
 'Bike Sharing',
 'Home Automation',
 'Trinidadian',
 'Beach Bars',
 'Software Development',
 'Bubble Tea',
 'Coffee & Tea Supplies',
 'Eyewear & Opticians',
 'Market Stalls',
 'South African',
 'Guitar Stores',
 'Pharmacy',
 'Accountants',
 'Marinas',
 'Art Schools',
 'Hot Tub & Pool',
 'Professional Sports Teams',
 'Shoe Shine',
 'Office Equipment',
 'Persian/Iranian',
 'Holistic Animal Care',
 'Phlebologists',
 'Door Sales/Installation',
 'Head Shops',
 'Private Schools',
 'Fondue',
 'Metal Fabricators',
 'Honduran',
 'Blow Dry/Out Services',
 'Mortgage Brokers',
 'Mini Golf',
 'Vacation Rentals',
 'Cryotherapy',
 'Cooking Classes',
 'Fuel Docks',
 'Tapas/Small Plates',
 'Basketball Courts',
 'Criminal Defense Law',
 'Waxing',
 'Comfort Food',
 'Gelato',
 'Laundry Services',
 'Dermatologists',
 'Squash',
 'Free Diving',
 'Emergency Pet Hospital',
 'Home Staging',
 'DIY Auto Shop',
 'Furniture Repair',
 'Valet Services',
 'Lawyers',
 'Pakistani',
 'Henna Artists',
 '& Probates',
 'Endocrinologists',
 'Public Services & Government',
 'Medical Foot Care',
 'Sandwiches',
 'Brazilian',
 'Window Washing',
 'Water Purification Services',
 'Animal Physical Therapy',
 'Colleges & Universities',
 'Irrigation',
 'Bar Crawl',
 'Bail Bondsmen',
 'Bars',
 'Duty-Free Shops',
 'General Festivals',
 'Bartending Schools',
 'Vinyl Records',
 'Wine Tasting Classes',
 'CPR Classes',
 'Wallpapering',
 'Roadside Assistance',
 'Backflow Services',
 'Rotisserie Chicken',
 'Pizza',
 'Officiants',
 'Embassy',
 'Professional Services',
 'Horse Boarding',
 'Childproofing',
 'Child Care & Day Care',
 'Eyebrow Services',
 'Japanese',
 'Discount Store',
 'Photo Booth Rentals',
 'Divorce & Family Law',
 'Modern European',
 'Auto Glass Services',
 'Shopping Centers',
 'Visitor Centers',
 'Pretzels',
 'Toxicologists',
 'Public Transportation',
 'Pet Stores',
 'Commissioned Artists',
 'Playgrounds',
 'Horse Equipment Shops',
 'Hydrotherapy',
 'Italian',
 'First Aid Classes',
 'Feng Shui',
 'Cafes',
 'Indonesian',
 'Pain Management',
 'Veterinarians',
 'Kickboxing',
 'Private Jet Charter',
 'Backshop',
 'Balloon Services',
 'Hong Kong Style Cafe',
 'Hot Pot',
 'Graphic Design',
 'Physical Therapy',
 'Supernatural Readings',
 'Telecommunications',
 'Architects',
 'Veterans Organizations',
 'Polish',
 'Reiki',
 'Tex-Mex',
 'Videos & Video Game Rental',
 'Landmarks & Historical Buildings',
 'Flowers & Gifts',
 'Swimming Lessons/Schools',
 'Studio Taping',
 'Summer Camps',
 'Self-defense Classes',
 'Landscaping',
 'Orthopedists',
 'Skate Shops',
 'Boxing',
 'Candy Stores',
 'Traditional Chinese Medicine',
 'Pool Halls',
 'Dive Bars',
 'Irish',
 'Psychics',
 'Sports Wear',
 'Rafting/Kayaking',
 'Saunas',
 'Bike Shop',
 'Leather Goods',
 'Aquarium Services',
 'Internet Service Providers',
 'Community Service/Non-Profit',
 'Food Court',
 'Condominiums',
 'Herbal Shops',
 'Adoption Services',
 'Reflexology',
 'Country Clubs',
 'British',
 'Barre Classes',
 'Tea Rooms',
 'Firewood',
 'Japanese Curry',
 'Religious Items',
 'Ski & Snowboard Shops',
 'Cocktail Bars',
 'Animal Shelters',
 'Florists',
 'Spiritual Shop',
 'Airport Terminals',
 'Costumes',
 'Bounce House Rentals',
 'Cheesesteaks',
 'Town Hall',
 'Boat Charters',
 'Generator Installation/Repair',
 'Nicaraguan',
 'Sri Lankan',
 'Toy Stores',
 'Shanghainese',
 'Estheticians',
 'Tires',
 'Hainan',
 'Emergency Rooms',
 'Hotel bar',
 'Check Cashing/Pay-day Loans',
 'Recycling Center',
 'Homeopathic',
 'Motorcycle Gear',
 'Canadian (New)',
 'Taekwondo',
 'Vascular Medicine',
 'Brewpubs',
 'Haunted Houses',
 'Wineries',
 'Homeless Shelters',
 'Salad',
 'Meat Shops',
 'Basque',
 'Dental Hygienists',
 'Asian Fusion',
 'Flight Instruction',
 'Traffic Ticketing Law',
 'Austrian',
 'Team Building Activities',
 'Soul Food',
 'Security Systems',
 'Horseback Riding',
 'Pop-up Shops',
 'Tableware',
 'Disc Golf',
 'Chimney Sweeps',
 'Pediatric Dentists',
 'Home Energy Auditors',
 'Badminton',
 'Smog Check Stations',
 'Historical Tours',
 'Personal Care Services',
 'Appliances & Repair',
 'Wholesalers',
 'Keys & Locksmiths',
 'Damage Restoration',
 'Specialty Schools',
 'Tennis',
 'Laser Tag',
 'Home Organization',
 'Trampoline Parks',
 'Vape Shops',
 'Linens',
 'Debt Relief Services',
 'Movers',
 'College Counseling',
 'Neurotologists',
 'Skydiving',
 'Gutter Services',
 'Surfing',
 'Caterers',
 'Junkyards',
 'Pulmonologist',
 'Hostels',
 'Placenta Encapsulations',
 'Sledding',
 'Countertop Installation',
 'International',
 'Walking Tours',
 'Souvenir Shops',
 'Hot Dogs',
 'Farming Equipment',
 'Service Stations',
 'Life Coach',
 'Tiki Bars',
 'Christmas Trees',
 'Beer Tours',
 'Muay Thai',
 'Karaoke',
 'Firearm Training',
 'Brazilian Jiu-jitsu',
 'Bagels',
 'Electronics Repair',
 'Moroccan',
 'Brewing Supplies',
 'Water Parks',
 'Dance Clubs',
 "Women's Clothing",
 'Osteopaths',
 'Nutritionists',
 'Screen Printing',
 'Lounges',
 'LAN Centers',
 'Home Decor',
 'Watches',
 'General Litigation',
 'Island Pub',
 'Mailbox Centers',
 '3D Printing',
 'Street Vendors',
 'Beaches',
 'Auto Security',
 'Pawn Shops',
 "Children's Museums",
 'Trainers',
 'Hardware Stores',
 'Boat Parts & Supplies',
 'Masonry/Concrete',
 'Hotels',
 'Contract Law',
 'Synagogues',
 'Local Flavor',
 'Speech Therapists',
 'Medical Spas',
 'Wine Tours',
 'Landscape Architects',
 'Accessories',
 'Shared Office Spaces',
 'Art Restoration',
 'Electricians',
 'Wills',
 'Boat Repair',
 'Currency Exchange',
 'IT Services & Computer Repair',
 'Motorcycle Dealers',
 'Hydro-jetting',
 'Jewelry',
 'Senegalese',
 'Pressure Washers',
 'Baby Gear & Furniture',
 'Massage',
 'Striptease Dancers',
 'Gold Buyers',
 'Passport & Visa Services',
 'Swimwear',
 'Whiskey Bars',
 'Afghan',
 'Bird Shops',
 'Recreation Centers',
 'Cooking Schools',
 'Indoor Playcentre',
 'Garage Door Services',
 'Hospitals',
 'Art Space Rentals',
 'Outdoor Furniture Stores',
 'Tanning Beds',
 'Vintage & Consignment',
 "Children's Clothing",
 'Photographers',
 'Jazz & Blues',
 'Mongolian',
 'Video Game Stores',
 'Climbing',
 'Australian',
 'Milkshake Bars',
 'Gun/Rifle Ranges',
 'Pop-Up Restaurants',
 'Community Centers',
 'Electricity Suppliers',
 'Country Dance Halls',
 'Lawn Services',
 'Yoga',
 'Jails & Prisons',
 'Antiques',
 'Gas Stations',
 'Restaurants',
 'Hydroponics',
 'Acai Bowls',
 'Zoos',
 'Counseling & Mental Health',
 'Tattoo Removal',
 'Podiatrists',
 'Homeowner Association',
 'Vitamins & Supplements',
 'Pita',
 'DUI Law',
 'Chocolatiers & Shops',
 'Pumpkin Patches',
 'Bartenders',
 'Patisserie/Cake Shop',
 'Undersea/Hyperbaric Medicine',
 'Taxidermy',
 'Diners',
 'Occupational Therapy',
 'Conveyor Belt Sushi',
 'Diagnostic Services',
 'Sports Clubs',
 'Soba',
 'Public Relations',
 'Grilling Equipment',
 'Event Photography',
 'Battery Stores',
 'Convenience Stores',
 'Parks',
 'Ethiopian',
 'Teppanyaki',
 'Investing',
 'Food Tours',
 'Juice Bars & Smoothies',
 'Amusement Parks',
 'Wholesale Stores',
 'Roofing',
 'Misting System Services',
 'Assisted Living Facilities',
 'Farm Equipment Repair',
 'Amateur Sports Teams',
 'Halal',
 'Proctologists',
 'Airsoft',
 'Event Planning & Services',
 'Mobile Phone Accessories',
 'Sports Bars',
 'Powder Coating',
 'Rolfing',
 'Waldorf Schools',
 'Art Tours',
 'Fabric Stores',
 'Dominican',
 'Honey',
 'Food Delivery Services',
 'Personal Injury Law',
 'Japanese Sweets',
 'Guns & Ammo',
 'Siding',
 'Spanish',
 'Ukrainian',
 'Hearing Aid Providers',
 'Packing Services',
 'Senior Centers',
 'Mortgage Lenders',
 'Calligraphy',
 'Bowling',
 'Beauty & Spas',
 'Caribbean',
 'Shredding Services',
 'Kids Activities',
 'Batting Cages',
 'Latin American',
 'Music & Video',
 'Product Design',
 'Live/Raw Food',
 'Puerto Rican',
 'Kitchen Supplies',
 'Pub Food',
 'Tutoring Centers',
 'Shutters',
 'Bistros',
 'Christmas Markets',
 'Floral Designers',
 'Hotels & Travel',
 'Festivals',
 'Commercial Real Estate',
 'Screen Printing/T-Shirt Printing',
 'Uniforms',
 'DJs',
 'Hospice',
 'Aerial Fitness',
 'Piano Bars',
 'Digitizing Services',
 'Personal Shopping',
 'Fire Protection Services',
 'Music Venues',
 'Auto Parts & Supplies',
 'Restaurant Supplies',
 'ATV Rentals/Tours',
 'Hawaiian',
 'Rehabilitation Center',
 'Signmaking',
 'Libraries',
 'Donuts',
 'Endodontists',
 'Water Delivery',
 'Mortuary Services',
 'Pubs',
 'Community Gardens',
 'Paddleboarding',
 'Auction Houses',
 'Poutineries',
 'Golf Equipment Shops',
 'CSA',
 'Meditation Centers',
 'Ethnic Grocery',
 'Mags',
 'EV Charging Stations',
 'Vehicle Shipping',
 'Tuscan',
 'Laundromat',
 'Bookstores',
 'Hiking',
 'Bicycles',
 'Doulas',
 'Party Characters',
 'Golf Cart Rentals',
 'Departments of Motor Vehicles',
 'Guamanian',
 'Pet Training',
 'Travel Services',
 'Fish & Chips',
 'TV Mounting',
 'Contractors',
 'Race Tracks',
 'Dance Wear',
 'RV Repair',
 'Clock Repair',
 'Armenian',
 'Music & DVDs',
 'Pet Transportation',
 'Appliances',
 'Rheumatologists',
 'Cinema',
 'Health Coach',
 'Appraisal Services',
 'Dry Cleaning & Laundry',
 'Gastropubs',
 'Vegetarian',
 'Environmental Abatement',
 'Bookkeepers',
 'Safe Stores',
 'Hair Salons',
 'Machine Shops',
 'Aerial Tours',
 ...}

In [18]:
# In this step, loop over the set and filter the df by those businesses that contain that category label
len(categories)

1300

In [ ]:
hasCategory = {'business_id':[], 'businessLabel':[]}
df3 = pd.DataFrame(hasCategory)

In [ ]:
# fucking filtering is too slow (pandas is fast --big fucking lol)
# see the two cells after thus one for how to do it in decent time
#for label in categories:
#    filt = (df['categories'].str.contains(label, na=False))
#    for business in df.loc[filt, 'business_id']:
#        df3 = df3.append({'business_id':business, 'businessLabel':label}, ignore_index = True)
#print('done')

In [22]:
#expect 30 seconds for this shit to finish
import pandas as pd
df = pd.read_csv("yelpdata/yelp-csv/yelp_academic_dataset_business.csv")

df_categories = df[['business_id', 'categories']]

business_id_labels = list() 
business_id_done = set() 


for i in df_categories.index: 
    business_id = df_categories.loc[i, 'business_id']
    categ_string = df_categories.loc[i, 'categories']
    if(str(categ_string) != "nan"): 
        categ_list = categ_string.split(', ')
        if not ( business_id in business_id_done) : 
            business_id_done.add(business_id)
            business_id_labels.extend(list(map(lambda label : (business_id, label) ,categ_list)))
            

business_id_labels_df = pd.DataFrame(business_id_labels, columns = ['business_id', 'businessLabel'])
business_id_labels_df.to_csv("business_id_categories.csv", index = False)
print('done')

done

In [23]:
# now get the fucking labels themselves
business_id_labels_df

                   business_id        businessLabel
0       1SWheh84yJXfytovILXOAQ                 Golf
1       1SWheh84yJXfytovILXOAQ          Active Life
2       QXAEGFB4oINsVuTFxEYKFQ       Specialty Food
3       QXAEGFB4oINsVuTFxEYKFQ          Restaurants
4       QXAEGFB4oINsVuTFxEYKFQ              Dim Sum
...                        ...                  ...
788354  Rv8s4io4G4mcUpiDbpzy7w               Trusts
788355  Rv8s4io4G4mcUpiDbpzy7w           & Probates
788356  Rv8s4io4G4mcUpiDbpzy7w              Lawyers
788357  Rv8s4io4G4mcUpiDbpzy7w       Legal Services
788358  Rv8s4io4G4mcUpiDbpzy7w  Estate Planning Law

[788359 rows x 2 columns]

In [26]:
# save the fucking categories
labels = business_id_labels_df['businessLabel']
labelsdf = pd.DataFrame(labels, columns = ['businessLabel'])
labelsdf.to_csv("category_labels.csv", index = False)
labelsdf

              businessLabel
0                      Golf
1               Active Life
2            Specialty Food
3               Restaurants
4                   Dim Sum
...                     ...
788354               Trusts
788355           & Probates
788356              Lawyers
788357       Legal Services
788358  Estate Planning Law

[788359 rows x 1 columns]

In [37]:
# now the fucking elite
df_users = pd.read_csv('yelpdata/yelp-csv/yelp_academic_dataset_user.csv')
df_elite = pd.DataFrame(df_users[['user_id','elite']], columns = ['user_id', 'elite'])
df_elite = df_elite.dropna()

In [38]:
df_elite

                       user_id                                    elite
0       l6BmjZMeQD3rDxWUbiAiow                           2015,2016,2017
4       MM4RJAeH6yuaN8oZDSt0RA                      2015,2016,2017,2018
5       0rK89TS8xqy1wI4nYI1wfw                      2015,2016,2017,2018
6       TEtzbpgA2BFBrC0y0sCbfw  2006,2007,2008,2009,2010,2011,2012,2013
8       T0gWkTHWRChVUe_Dn1F8nw       2006,2007,2008,2009,2010,2011,2012
...                        ...                                      ...
778085  lLevwsNW8gyvBRRY5WFSgg                                     2018
778225  TvKpazAvQLSnKwodcuuEYg                                     2018
778471  xJEbA3Dwldz_twXsHNaJhA                                     2018
778589  mSaD4g37jCy4-95pB6NWKA                                     2018
778643  7kACk6ZydEKDwJ7tz5r1pw                                     2018

[70559 rows x 2 columns]

In [44]:
df_elite['elite'].str.split(',', expand = True)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,2015,2016,2017,None,None,None,None,None,None,None,None,None,None
4,2015,2016,2017,2018,None,None,None,None,None,None,None,None,None
5,2015,2016,2017,2018,None,None,None,None,None,None,None,None,None
6,2006,2007,2008,2009,2010,2011,2012,2013,None,None,None,None,None
8,2006,2007,2008,2009,2010,2011,2012,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
778085,2018,None,None,None,None,None,None,None,None,None,None,None,None
778225,2018,None,None,None,None,None,None,None,None,None,None,None,None
778471,2018,None,None,None,None,None,None,None,None,None,None,None,None
778589,2018,None,None,None,None,None,None,None,None,None,None,None,None
778643,2018,None,None,None,None,None,None,None,None,None,None,None,None

In [46]:
yearset = set()
def getAllYears(years):
    if (not isinstance(years, float)):
        yrlist = str(years).split(',')
        yearset.update(yrlist)
df_elite['elite'].apply(getAllYears)
# display all the years of eliteshitmanship
yearset

{'2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018'}

In [58]:
# note to self: only call dataframe.append in a loop when you want to kill yourself
list_user_year = list()
for index, row in df_elite.iterrows():
    listyrs = row['elite'].split(',')
    list_user_year.extend(list(map(lambda label : (row['user_id'], label) ,listyrs)))
df_iselite = pd.DataFrame(list_user_year, columns = ['user_id', 'elite_year'])
print('done')

done

In [66]:
df_iselite.to_csv('isElite.csv', index = False)
df_iselite

                       user_id elite_year
0       l6BmjZMeQD3rDxWUbiAiow       2015
1       l6BmjZMeQD3rDxWUbiAiow       2016
2       l6BmjZMeQD3rDxWUbiAiow       2017
3       MM4RJAeH6yuaN8oZDSt0RA       2015
4       MM4RJAeH6yuaN8oZDSt0RA       2016
...                        ...        ...
223172  lLevwsNW8gyvBRRY5WFSgg       2018
223173  TvKpazAvQLSnKwodcuuEYg       2018
223174  xJEbA3Dwldz_twXsHNaJhA       2018
223175  mSaD4g37jCy4-95pB6NWKA       2018
223176  7kACk6ZydEKDwJ7tz5r1pw       2018

[223177 rows x 2 columns]

In [68]:
df_elite_years = pd.DataFrame(yearset, columns = ['elite_year'])
df_elite_years.to_csv('elite.csv', index=False)
df_elite_years

   elite_year
0        2006
1        2015
2        2012
3        2017
4        2014
5        2016
6        2013
7        2008
8        2018
9        2007
10       2009
11       2010
12       2011