In [78]:
import pandas as pd
df = pd.read_csv('../../yelpdata/yelp-csv/yelp_academic_dataset_business.csv')
df

,address,attributes,business_id,categories,city,hours,is_open,latitude,longitude,name,postal_code,review_count,stars,state
0,2818 E Camino Acequia Drive,{},1SWheh84yJXfytovILXOAQ,"Golf, Active Life",Phoenix,NaN,0,33.522143,-112.018481,Arizona Biltmore Golf Club,85016,5,3.0,AZ
1,30 Eglinton Avenue W,"{'GoodForMeal': ""{'dessert': False, 'latenight...",QXAEGFB4oINsVuTFxEYKFQ,"Specialty Food, Restaurants, Dim Sum, Imported...",Mississauga,"{'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W...",1,43.605499,-79.652289,Emerald Chinese Restaurant,L5R 3E7,128,2.5,ON
2,"1210 8th Street SW, Unit 220","{'BusinessParking': ""{'garage': False, 'street...",fcXOEZdXYeZqnQ3lGlOXmg,"Local Services, Professional Services, Compute...",Calgary,"{'Monday': '9:0-17:0', 'Tuesday': '9:0-17:0', ...",1,51.041771,-114.081109,Nucleus Information Service,T2R 1L3,5,2.0,AB
3,"6955 N Durango Dr, Ste 1116","{'BusinessParking': ""{'garage': False, 'street...",f2ZWZPENViL92BrFsIgR6w,"Beauty & Spas, Hair Salons",Las Vegas,"{'Monday': '8:30-20:0', 'Tuesday': '8:30-20:0'...",1,36.287312,-115.289540,Amazing Cuts,89149,116,4.5,NV
4,4 E University Dr,{},6KgGE8B1RsR7jc9R5nuH0Q,"American (Traditional), Restaurants",Tempe,NaN,0,33.422192,-111.939615,Ruby Tuesday,85281,9,2.5,AZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192604,521 St. Catherine Street W,"{'Ambience': ""{'romantic': False, 'intimate': ...",wWV90q48ugyxyXW6gZav8w,"Restaurants, Venezuelan, Latin American",Montréal,NaN,0,45.504597,-73.568456,Arepas,H3B 1A6,15,3.5,QC
192605,244 Victoria Street,{},phSaT3I_y6To1J2OdeFSUQ,"Arts & Entertainment, Performing Arts",Toronto,NaN,1,43.655290,-79.379541,Ed Mirvish Theatre,M5B 1V8,58,4.0,ON
192606,10210 South 50th Pl,NaN,oU6Q3ymg1Qsh1EUI6oQwQg,"Education, Middle Schools & High Schools",Phoenix,"{'Monday': '7:30-17:30', 'Tuesday': '7:30-17:3...",1,33.354284,-111.975538,BASIS Ahwatukee,85044,3,2.5,AZ
192607,"6670 S Tenaya Way, Ste 120, The Body Spa","{'BusinessParking': ""{'garage': False, 'street...",gdiOk0n7DmNE9w8xeHWkvw,"Beauty & Spas, Eyelash Service, Waxing, Esthet...",Las Vegas,"{'Monday': '0:0-0:0', 'Tuesday': '9:0-19:0', '...",1,36.066952,-115.251008,Brows Redefined,89113,15,5.0,NV
192608,"14050 N 83rd Ave, Ste 290",NaN,Rv8s4io4G4mcUpiDbpzy7w,"Professional Services, Wills, Trusts, & Probat...",Peoria,"{'Monday': '8:0-18:0', 'Tuesday': '8:0-18:0', ...",1,33.612226,-112.238145,Affordable Estate Planning,85381,3,5.0,AZ

In [79]:
## it was missing address so I put it there 
## technically this shit stadium has a set of address from 12030 to 12040 but in the assumptions we can say we assume only the main entrance of the business should be considered
df.loc[119357, ['city', 'address', 'postal_code']] = ['Mesa', '12033 S Sossaman Rd', '85212']
df.loc[119357]

address                                       12033 S Sossaman Rd
attributes      {'BusinessParking': "{'garage': False, 'street...
business_id                                WpC53SqwoCY5AuYIFr_1eA
categories                                    Soccer, Active Life
city                                                         Mesa
hours                                                         NaN
is_open                                                         1
latitude                                                  33.3381
longitude                                                -111.678
name                                 NSFC Strikers Soccer Complex
postal_code                                                 85212
review_count                                                    3
stars                                                         2.5
state                                                          AZ
Name: 119357, dtype: object

In [80]:
dfhasLocAB = pd.DataFrame(df[['latitude','longitude', 'business_id', 'address', 'city', 'state']])
dfhasLocAB

,latitude,longitude,business_id,address,city,state
0,33.522143,-112.018481,1SWheh84yJXfytovILXOAQ,2818 E Camino Acequia Drive,Phoenix,AZ
1,43.605499,-79.652289,QXAEGFB4oINsVuTFxEYKFQ,30 Eglinton Avenue W,Mississauga,ON
2,51.041771,-114.081109,fcXOEZdXYeZqnQ3lGlOXmg,"1210 8th Street SW, Unit 220",Calgary,AB
3,36.287312,-115.289540,f2ZWZPENViL92BrFsIgR6w,"6955 N Durango Dr, Ste 1116",Las Vegas,NV
4,33.422192,-111.939615,6KgGE8B1RsR7jc9R5nuH0Q,4 E University Dr,Tempe,AZ
...,...,...,...,...,...,...
192604,45.504597,-73.568456,wWV90q48ugyxyXW6gZav8w,521 St. Catherine Street W,Montréal,QC
192605,43.655290,-79.379541,phSaT3I_y6To1J2OdeFSUQ,244 Victoria Street,Toronto,ON
192606,33.354284,-111.975538,oU6Q3ymg1Qsh1EUI6oQwQg,10210 South 50th Pl,Phoenix,AZ
192607,36.066952,-115.251008,gdiOk0n7DmNE9w8xeHWkvw,"6670 S Tenaya Way, Ste 120, The Body Spa",Las Vegas,NV
192608,33.612226,-112.238145,Rv8s4io4G4mcUpiDbpzy7w,"14050 N 83rd Ave, Ste 290",Peoria,AZ

In [81]:
dfhasLocAB.rename(columns={'address':'streetAddr', 'city':'cityName', 'state':'stateName'}, inplace=True)
dfhasLocAB.to_csv('hasLocationAB.csv', index=False)
dfhasLocAB

,latitude,longitude,business_id,streetAddr,cityName,stateName
0,33.522143,-112.018481,1SWheh84yJXfytovILXOAQ,2818 E Camino Acequia Drive,Phoenix,AZ
1,43.605499,-79.652289,QXAEGFB4oINsVuTFxEYKFQ,30 Eglinton Avenue W,Mississauga,ON
2,51.041771,-114.081109,fcXOEZdXYeZqnQ3lGlOXmg,"1210 8th Street SW, Unit 220",Calgary,AB
3,36.287312,-115.289540,f2ZWZPENViL92BrFsIgR6w,"6955 N Durango Dr, Ste 1116",Las Vegas,NV
4,33.422192,-111.939615,6KgGE8B1RsR7jc9R5nuH0Q,4 E University Dr,Tempe,AZ
...,...,...,...,...,...,...
192604,45.504597,-73.568456,wWV90q48ugyxyXW6gZav8w,521 St. Catherine Street W,Montréal,QC
192605,43.655290,-79.379541,phSaT3I_y6To1J2OdeFSUQ,244 Victoria Street,Toronto,ON
192606,33.354284,-111.975538,oU6Q3ymg1Qsh1EUI6oQwQg,10210 South 50th Pl,Phoenix,AZ
192607,36.066952,-115.251008,gdiOk0n7DmNE9w8xeHWkvw,"6670 S Tenaya Way, Ste 120, The Body Spa",Las Vegas,NV
192608,33.612226,-112.238145,Rv8s4io4G4mcUpiDbpzy7w,"14050 N 83rd Ave, Ste 290",Peoria,AZ

In [82]:
############################### table hasLocationAB done #################################

In [83]:
dfaddrAB = pd.DataFrame(df[['postal_code','address', 'city', 'state']])
dfaddrAB

,postal_code,address,city,state
0,85016,2818 E Camino Acequia Drive,Phoenix,AZ
1,L5R 3E7,30 Eglinton Avenue W,Mississauga,ON
2,T2R 1L3,"1210 8th Street SW, Unit 220",Calgary,AB
3,89149,"6955 N Durango Dr, Ste 1116",Las Vegas,NV
4,85281,4 E University Dr,Tempe,AZ
...,...,...,...,...
192604,H3B 1A6,521 St. Catherine Street W,Montréal,QC
192605,M5B 1V8,244 Victoria Street,Toronto,ON
192606,85044,10210 South 50th Pl,Phoenix,AZ
192607,89113,"6670 S Tenaya Way, Ste 120, The Body Spa",Las Vegas,NV
192608,85381,"14050 N 83rd Ave, Ste 290",Peoria,AZ

In [84]:
dfaddrAB.rename(columns={'address':'streetAddr', 'city':'cityName', 'state':'stateName', 'postal_code':'postalCode'}, inplace=True)
dfaddrAB

,postalCode,streetAddr,cityName,stateName
0,85016,2818 E Camino Acequia Drive,Phoenix,AZ
1,L5R 3E7,30 Eglinton Avenue W,Mississauga,ON
2,T2R 1L3,"1210 8th Street SW, Unit 220",Calgary,AB
3,89149,"6955 N Durango Dr, Ste 1116",Las Vegas,NV
4,85281,4 E University Dr,Tempe,AZ
...,...,...,...,...
192604,H3B 1A6,521 St. Catherine Street W,Montréal,QC
192605,M5B 1V8,244 Victoria Street,Toronto,ON
192606,85044,10210 South 50th Pl,Phoenix,AZ
192607,89113,"6670 S Tenaya Way, Ste 120, The Body Spa",Las Vegas,NV
192608,85381,"14050 N 83rd Ave, Ste 290",Peoria,AZ

In [85]:
# remove duplicates
dfaddrAB.drop_duplicates(subset = ['streetAddr', 'cityName', 'stateName'], keep ='first', inplace = True)
dfaddrAB.to_csv('addressAB.csv', index=False)
dfaddrAB
###################################### table addressAB done ###########################################

,postalCode,streetAddr,cityName,stateName
0,85016,2818 E Camino Acequia Drive,Phoenix,AZ
1,L5R 3E7,30 Eglinton Avenue W,Mississauga,ON
2,T2R 1L3,"1210 8th Street SW, Unit 220",Calgary,AB
3,89149,"6955 N Durango Dr, Ste 1116",Las Vegas,NV
4,85281,4 E University Dr,Tempe,AZ
...,...,...,...,...
192603,85210,440 S Extension Rd,Mesa,AZ
192604,H3B 1A6,521 St. Catherine Street W,Montréal,QC
192605,M5B 1V8,244 Victoria Street,Toronto,ON
192606,85044,10210 South 50th Pl,Phoenix,AZ
192607,89113,"6670 S Tenaya Way, Ste 120, The Body Spa",Las Vegas,NV

In [86]:
#actually a shit ton of values are nan as you can see so I discard them
import numpy as np
for index, row in dfaddrAB.iterrows():
    if (type(row['streetAddr']) is float):
        print('garbage present with index2 '+ str(index))
        print(str(row))
print('done')

garbage present with index2 27
postalCode    85204
streetAddr      NaN
cityName       Mesa
stateName        AZ
Name: 27, dtype: object
garbage present with index2 28
postalCode        28273
streetAddr          NaN
cityName      Charlotte
stateName            NC
Name: 28, dtype: object
garbage present with index2 35
postalCode    85284
streetAddr      NaN
cityName      Tempe
stateName        AZ
Name: 35, dtype: object
garbage present with index2 43
postalCode        89102
streetAddr          NaN
cityName      Las Vegas
stateName            NV
Name: 43, dtype: object
garbage present with index2 47
postalCode      85040
streetAddr        NaN
cityName      Phoenix
stateName          AZ
Name: 47, dtype: object
garbage present with index2 69
postalCode        89012
streetAddr          NaN
cityName      Henderson
stateName            NV
Name: 69, dtype: object
garbage present with index2 79
postalCode     J4Y 1A2
streetAddr         NaN
cityName      Montréal
stateName           QC
Name: 79, dtype: object
garbage present with index2 149
postalCode         85250
streetAddr           NaN
cityName      Scottsdale
stateName             AZ
Name: 149, dtype: object
garbage present with index2 159
postalCode      85299
streetAddr        NaN
cityName      Gilbert
stateName          AZ
Name: 159, dtype: object
garbage present with index2 208
postalCode      85351
streetAddr        NaN
cityName      Suncity
stateName          AZ
Name: 208, dtype: object
garbage present with index2 245
postalCode        T3J
streetAddr        NaN
cityName      Calgary
stateName          AB
Name: 245, dtype: object
garbage present with index2 282
postalCode        61824
streetAddr          NaN
cityName      Champaign
stateName            IL
Name: 282, dtype: object
garbage present with index2 429
postalCode       85286
streetAddr         NaN
cityName      Chandler
stateName           AZ
Name: 429, dtype: object
garbage present with index2 492
postalCode        NaN
streetAddr        NaN
cityName      Toronto
stateName          ON
Name: 492, dtype: object
garbage present with index2 566
postalCode       85392
streetAddr         NaN
cityName      Avondale
stateName           AZ
Name: 566, dtype: object
garbage present with index2 848
postalCode       85388
streetAddr         NaN
cityName      Surprise
stateName           AZ
Name: 848, dtype: object
garbage present with index2 963
postalCode            85375
streetAddr              NaN
cityName      Sun City West
stateName                AZ
Name: 963, dtype: object
garbage present with index2 1432
postalCode         85337
streetAddr           NaN
cityName      Cave Creek
stateName             AZ
Name: 1432, dtype: object
garbage present with index2 1503
postalCode      53725
streetAddr        NaN
cityName      Madison
stateName          WI
Name: 1503, dtype: object
garbage present with index2 1610
postalCode            44070
streetAddr              NaN
cityName      North Olmsted
stateName                OH
Name: 1610, dtype: object
garbage present with index2 1756
postalCode       85301
streetAddr         NaN
cityName      Glendale
stateName           AZ
Name: 1756, dtype: object
garbage present with index2 2009
postalCode     85373
streetAddr       NaN
cityName      Peoria
stateName         AZ
Name: 2009, dtype: object
garbage present with index2 2351
postalCode        28031
streetAddr          NaN
cityName      Cornelius
stateName            NC
Name: 2351, dtype: object
garbage present with index2 2622
postalCode          15290
streetAddr            NaN
cityName      Pittsburgh
stateName              PA
Name: 2622, dtype: object
garbage present with index2 2687
postalCode              89031
streetAddr                NaN
cityName      North Las Vegas
stateName                  NV
Name: 2687, dtype: object
garbage present with index2 2750
postalCode    L3R 4S8
streetAddr        NaN
cityName      Markham
stateName          ON
Name: 2750, dtype: object
garbage present with index2 2822
postalCode       85395
streetAddr         NaN
cityName      Goodyear
stateName           AZ
Name: 2822, dtype: object
garbage present with index2 3171
postalCode             44223
streetAddr               NaN
cityName      Cuyahoga Falls
stateName                 OH
Name: 3171, dtype: object
garbage present with index2 3653
postalCode         15230
streetAddr           NaN
cityName      Pittsburgh
stateName             PA
Name: 3653, dtype: object
garbage present with index2 4262
postalCode             85268
streetAddr               NaN
cityName      Fountain Hills
stateName                 AZ
Name: 4262, dtype: object
garbage present with index2 4264
postalCode      28012
streetAddr        NaN
cityName      Belmont
stateName          NC
Name: 4264, dtype: object
garbage present with index2 4540
postalCode                 85005
streetAddr                   NaN
cityName      Phoenix Metro Area
stateName                     AZ
Name: 4540, dtype: object
garbage present with index2 4608
postalCode        44113
streetAddr          NaN
cityName      Cleveland
stateName            OH
Name: 4608, dtype: object
garbage present with index2 4613
postalCode        53711
streetAddr          NaN
cityName      Fitchburg
stateName            WI
Name: 4613, dtype: object
garbage present with index2 4799
postalCode     28173
streetAddr       NaN
cityName      Waxhaw
stateName         NC
Name: 4799, dtype: object
garbage present with index2 5126
postalCode          15146
streetAddr            NaN
cityName      Monroeville
stateName              PA
Name: 5126, dtype: object
garbage present with index2 5362
postalCode           89005
streetAddr             NaN
cityName      Boulder City
stateName               NV
Name: 5362, dtype: object
garbage present with index2 5412
postalCode           28079
streetAddr             NaN
cityName      Indian Trail
stateName               NC
Name: 5412, dtype: object
garbage present with index2 5906
postalCode        L5V 2K6
streetAddr            NaN
cityName      Mississauga
stateName              ON
Name: 5906, dtype: object
garbage present with index2 6122
postalCode       85372
streetAddr         NaN
cityName      Sun City
stateName           AZ
Name: 6122, dtype: object
garbage present with index2 6234
postalCode        28227
streetAddr          NaN
cityName      Mint Hill
stateName            NC
Name: 6234, dtype: object
garbage present with index2 6443
postalCode       NaN
streetAddr       NaN
cityName      Laveen
stateName         AZ
Name: 6443, dtype: object
garbage present with index2 6748
postalCode       44145
streetAddr         NaN
cityName      Westlake
stateName           OH
Name: 6748, dtype: object
garbage present with index2 7134
postalCode       85353
streetAddr         NaN
cityName      Tolleson
stateName           AZ
Name: 7134, dtype: object
garbage present with index2 7170
postalCode              85340
streetAddr                NaN
cityName      Litchfield Park
stateName                  AZ
Name: 7170, dtype: object
garbage present with index2 8070
postalCode    44129
streetAddr      NaN
cityName      Parma
stateName        OH
Name: 8070, dtype: object
garbage present with index2 8247
postalCode       28105
streetAddr         NaN
cityName      Matthews
stateName           NC
Name: 8247, dtype: object
garbage present with index2 9089
postalCode               85005
streetAddr                 NaN
cityName      Estrella Village
stateName                   AZ
Name: 9089, dtype: object
garbage present with index2 9399
postalCode            15636
streetAddr              NaN
cityName      Harrison City
stateName                PA
Name: 9399, dtype: object
garbage present with index2 9494
postalCode     61801
streetAddr       NaN
cityName      Urbana
stateName         IL
Name: 9494, dtype: object
garbage present with index2 10047
postalCode    44240
streetAddr      NaN
cityName       Kent
stateName        OH
Name: 10047, dtype: object
garbage present with index2 10073
postalCode               44125
streetAddr                 NaN
cityName      Garfield Heights
stateName                   OH
Name: 10073, dtype: object
garbage present with index2 10281
postalCode                H9B 1A2
streetAddr                    NaN
cityName      Dollard-des Ormeaux
stateName                      QC
Name: 10281, dtype: object
garbage present with index2 10310
postalCode        15030
streetAddr          NaN
cityName      Creighton
stateName            PA
Name: 10310, dtype: object

garbage present with index2 11210
postalCode              85253
streetAddr                NaN
cityName      Paradise Valley
stateName                  AZ
Name: 11210, dtype: object
garbage present with index2 11293
postalCode        44012
streetAddr          NaN
cityName      Avon Lake
stateName            OH
Name: 11293, dtype: object
garbage present with index2 11795
postalCode        85335
streetAddr          NaN
cityName      El Mirage
stateName            AZ
Name: 11795, dtype: object
garbage present with index2 12008
postalCode            44022
streetAddr              NaN
cityName      Chagrin Falls
stateName                OH
Name: 12008, dtype: object
garbage present with index2 12146
postalCode       15106
streetAddr         NaN
cityName      Carnegie
stateName           PA
Name: 12146, dtype: object
garbage present with index2 12754
postalCode      44001
streetAddr        NaN
cityName      Amherst
stateName          OH
Name: 12754, dtype: object
garbage present with index2 13115
postalCode           28078
streetAddr             NaN
cityName      Huntersville
stateName               NC
Name: 13115, dtype: object
garbage present with index2 13140
postalCode        89004
streetAddr          NaN
cityName      Summerlin
stateName            NV
Name: 13140, dtype: object
garbage present with index2 15025
postalCode            15068
streetAddr              NaN
cityName      Lower Burrell
stateName                PA
Name: 15025, dtype: object
garbage present with index2 15205
postalCode     85236
streetAddr       NaN
cityName      Higley
stateName         AZ
Name: 15205, dtype: object
garbage present with index2 15261
postalCode        28134
streetAddr          NaN
cityName      Pineville
stateName            NC
Name: 15261, dtype: object
garbage present with index2 15852
postalCode          44124
streetAddr            NaN
cityName      Pepper Pike
stateName              OH
Name: 15852, dtype: object
garbage present with index2 16926
postalCode      28025
streetAddr        NaN
cityName      Concord
stateName          NC
Name: 16926, dtype: object
garbage present with index2 16935
postalCode         28210
streetAddr           NaN
cityName      charlottte
stateName             NC
Name: 16935, dtype: object
garbage present with index2 17286
postalCode     44256
streetAddr       NaN
cityName      Medina
stateName         OH
Name: 17286, dtype: object
garbage present with index2 17317
postalCode          44140
streetAddr            NaN
cityName      Bay Village
stateName              OH
Name: 17317, dtype: object
garbage present with index2 17447
postalCode        44212
streetAddr          NaN
cityName      Brunswick
stateName            OH
Name: 17447, dtype: object
garbage present with index2 17601
postalCode     53593
streetAddr       NaN
cityName      Verona
stateName         WI
Name: 17601, dtype: object
garbage present with index2 18968
postalCode           15122
streetAddr             NaN
cityName      West Mifflin
stateName               PA
Name: 18968, dtype: object
garbage present with index2 19145
postalCode          L3X
streetAddr          NaN
cityName      Newmarket
stateName            ON
Name: 19145, dtype: object
garbage present with index2 19402
postalCode         NaN
streetAddr         NaN
cityName      Nobleton
stateName           ON
Name: 19402, dtype: object
garbage present with index2 20323
postalCode          89030
streetAddr            NaN
cityName      N Las Vegas
stateName              NV
Name: 20323, dtype: object
garbage present with index2 20782
postalCode    L6A 4B3
streetAddr        NaN
cityName      Vaughan
stateName          ON
Name: 20782, dtype: object
garbage present with index2 21008
postalCode             85339
streetAddr               NaN
cityName      Laveen Village
stateName                 AZ
Name: 21008, dtype: object
garbage present with index2 21506
postalCode    L4G 6Y1
streetAddr        NaN
cityName       Aurora
stateName          ON
Name: 21506, dtype: object
garbage present with index2 21755
postalCode       NaN
streetAddr       NaN
cityName      Whitby
stateName         ON
Name: 21755, dtype: object
garbage present with index2 22308
postalCode      61853
streetAddr        NaN
cityName      Mahomet
stateName          IL
Name: 22308, dtype: object
garbage present with index2 22992
postalCode    44320
streetAddr      NaN
cityName      Akron
stateName        OH
Name: 22992, dtype: object
garbage present with index2 23184
postalCode        L7C
streetAddr        NaN
cityName      Caledon
stateName          ON
Name: 23184, dtype: object
garbage present with index2 26298
postalCode               15642
streetAddr                 NaN
cityName      North Huntingdon
stateName                   PA
Name: 26298, dtype: object
garbage present with index2 26528
postalCode        29715
streetAddr          NaN
cityName      Fort Mill
stateName            SC
Name: 26528, dtype: object
garbage present with index2 27432
postalCode    44011
streetAddr      NaN
cityName       Avon
stateName        OH
Name: 27432, dtype: object
garbage present with index2 27458
postalCode        T4B
streetAddr        NaN
cityName      Airdrie
stateName          AB
Name: 27458, dtype: object
garbage present with index2 28068
postalCode       44107
streetAddr         NaN
cityName      Lakewood
stateName           OH
Name: 28068, dtype: object
garbage present with index2 30162
postalCode          89052
streetAddr            NaN
cityName      Seven Hills
stateName              NV
Name: 30162, dtype: object
garbage present with index2 30223
postalCode             NaN
streetAddr             NaN
cityName      Strongsville
stateName               OH
Name: 30223, dtype: object
garbage present with index2 30232
postalCode        85363
streetAddr          NaN
cityName      Youngtown
stateName            AZ
Name: 30232, dtype: object
garbage present with index2 31637
postalCode            85264
streetAddr              NaN
cityName      Fort McDowell
stateName                AZ
Name: 31637, dtype: object
garbage present with index2 32905
postalCode         85020
streetAddr           NaN
cityName      Sunnyslope
stateName             AZ
Name: 32905, dtype: object
garbage present with index2 33249
postalCode     44237
streetAddr       NaN
cityName      Hudson
stateName         OH
Name: 33249, dtype: object
garbage present with index2 33572
postalCode          53590
streetAddr            NaN
cityName      Sun Prairie
stateName              WI
Name: 33572, dtype: object
garbage present with index2 33747
postalCode       85016
streetAddr         NaN
cityName      Phoeniix
stateName           AZ
Name: 33747, dtype: object
garbage present with index2 33814
postalCode       NaN
streetAddr       NaN
cityName      Verdun
stateName         QC
Name: 33814, dtype: object
garbage present with index2 35893
postalCode         15108
streetAddr           NaN
cityName      Coraopolis
stateName             PA
Name: 35893, dtype: object
garbage present with index2 36038
postalCode     53575
streetAddr       NaN
cityName      Oregon
stateName         WI
Name: 36038, dtype: object
garbage present with index2 36605
postalCode        M1W 4C1
streetAddr            NaN
cityName      Scarborough
stateName              ON
Name: 36605, dtype: object
garbage present with index2 37193
postalCode        29715
streetAddr          NaN
cityName      Fort Mill
stateName            NC
Name: 37193, dtype: object
garbage present with index2 37786
postalCode                    H9X 1M2
streetAddr                        NaN
cityName      Sainte-Anne-de-Bellevue
stateName                          QC
Name: 37786, dtype: object
garbage present with index2 38707
postalCode         44212
streetAddr           NaN
cityName      Nationwide
stateName             CA
Name: 38707, dtype: object
garbage present with index2 39278
postalCode            44137
streetAddr              NaN
cityName      Maple Heights
stateName                OH
Name: 39278, dtype: object
garbage present with index2 39559
postalCode         85064
streetAddr           NaN
cityName      Valleywide
stateName             AZ
Name: 39559, dtype: object
garbage present with index2 40906
postalCode        15037
streetAddr          NaN
cityName      Elizabeth
stateName            PA
Name: 40906, dtype: object
garbage present with index2 41143
postalCode             85140
streetAddr               NaN
cityName      San Tan Valley
stateName                 AZ
Name: 41143, dtype: object
garbage present with index2 41154
postalCode          44224
streetAddr            NaN
cityName      Silver Lake
stateName              OH
Name: 41154, dtype: object

garbage present with index2 41862
postalCode          90001
streetAddr            NaN
cityName      Los Angeles
stateName              CA
Name: 41862, dtype: object
garbage present with index2 42173
postalCode            53527
streetAddr              NaN
cityName      Cottage Grove
stateName                WI
Name: 42173, dtype: object
garbage present with index2 42853
postalCode           NaN
streetAddr           NaN
cityName      Boisbriand
stateName             QC
Name: 42853, dtype: object
garbage present with index2 43037
postalCode          L4C 3B3
streetAddr              NaN
cityName      Richmond Hill
stateName                ON
Name: 43037, dtype: object
garbage present with index2 43289
postalCode         44067
streetAddr           NaN
cityName      Northfield
stateName             OH
Name: 43289, dtype: object
garbage present with index2 43322
postalCode       53597
streetAddr         NaN
cityName      Waunakee
stateName           WI
Name: 43322, dtype: object
garbage present with index2 43886
postalCode         L6R
streetAddr         NaN
cityName      Brampton
stateName           ON
Name: 43886, dtype: object
garbage present with index2 44253
postalCode          44131
streetAddr            NaN
cityName      Seven Hills
stateName              OH
Name: 44253, dtype: object
garbage present with index2 44721
postalCode         15133
streetAddr           NaN
cityName      McKeesport
stateName             PA
Name: 44721, dtype: object
garbage present with index2 44913
postalCode             L9N 1K4
streetAddr                 NaN
cityName      East Gwillimbury
stateName                   ON
Name: 44913, dtype: object
garbage present with index2 45865
postalCode        44286
streetAddr          NaN
cityName      Richfield
stateName            OH
Name: 45865, dtype: object
garbage present with index2 46232
postalCode        NaN
streetAddr        NaN
cityName      Buckeye
stateName          AZ
Name: 46232, dtype: object
garbage present with index2 46991
postalCode           L5B
streetAddr           NaN
cityName      Cooksville
stateName             ON
Name: 46991, dtype: object
garbage present with index2 47197
postalCode               44124
streetAddr                 NaN
cityName      Mayfield Heights
stateName                   OH
Name: 47197, dtype: object
garbage present with index2 47379
postalCode      85355
streetAddr        NaN
cityName      Waddell
stateName          AZ
Name: 47379, dtype: object
garbage present with index2 47741
postalCode           85260
streetAddr             NaN
cityName      Grand Canyon
stateName               AZ
Name: 47741, dtype: object
garbage present with index2 47890
postalCode        53589
streetAddr          NaN
cityName      Stoughton
stateName            WI
Name: 47890, dtype: object
garbage present with index2 48120
postalCode                        NaN
streetAddr                        NaN
cityName      Henderson and Las vegas
stateName                          NV
Name: 48120, dtype: object
garbage present with index2 48667
postalCode     28110
streetAddr       NaN
cityName      Monroe
stateName         NC
Name: 48667, dtype: object
garbage present with index2 48744
postalCode    33608
streetAddr      NaN
cityName      Tampa
stateName        FL
Name: 48744, dtype: object
garbage present with index2 48972
postalCode       44144
streetAddr         NaN
cityName      Brooklyn
stateName           OH
Name: 48972, dtype: object
garbage present with index2 49561
postalCode    OL2 6PX
streetAddr        NaN
cityName       Oldham
stateName         XGM
Name: 49561, dtype: object
garbage present with index2 50433
postalCode        44092
streetAddr          NaN
cityName      Wickliffe
stateName            OH
Name: 50433, dtype: object
garbage present with index2 50480
postalCode     44035
streetAddr       NaN
cityName      Elyria
stateName         OH
Name: 50480, dtype: object
garbage present with index2 50611
postalCode      44024
streetAddr        NaN
cityName      Chardon
stateName          OH
Name: 50611, dtype: object
garbage present with index2 51105
postalCode          15332
streetAddr            NaN
cityName      Finleyville
stateName              PA
Name: 51105, dtype: object
garbage present with index2 51410
postalCode        53597
streetAddr          NaN
cityName      Middleton
stateName            WI
Name: 51410, dtype: object
garbage present with index2 51708
postalCode        44122
streetAddr          NaN
cityName      Beachwood
stateName            OH
Name: 51708, dtype: object
garbage present with index2 52196
postalCode          15668
streetAddr            NaN
cityName      Murrysville
stateName              PA
Name: 52196, dtype: object
garbage present with index2 55954
postalCode       T2H 0L1
streetAddr           NaN
cityName      SW Calgary
stateName             AB
Name: 55954, dtype: object
garbage present with index2 56224
postalCode               85225
streetAddr                 NaN
cityName      Chandler-Gilbert
stateName                   AZ
Name: 56224, dtype: object
garbage present with index2 56608
postalCode                     NaN
streetAddr                     NaN
cityName      Central City Village
stateName                       AZ
Name: 56608, dtype: object
garbage present with index2 57685
postalCode               85266
streetAddr                 NaN
cityName      North Scottsdale
stateName                   AZ
Name: 57685, dtype: object
garbage present with index2 58737
postalCode       15317
streetAddr         NaN
cityName      McMurray
stateName           PA
Name: 58737, dtype: object
garbage present with index2 60795
postalCode             85083
streetAddr               NaN
cityName      Stetson Valley
stateName                 AZ
Name: 60795, dtype: object
garbage present with index2 60868
postalCode               44094
streetAddr                 NaN
cityName      Willoughby Hills
stateName                   OH
Name: 60868, dtype: object
garbage present with index2 61020
postalCode            28110
streetAddr              NaN
cityName      Wesley Chapel
stateName                NC
Name: 61020, dtype: object
garbage present with index2 61174
postalCode         89199
streetAddr           NaN
cityName      Las Vegas
stateName             NV
Name: 61174, dtype: object
garbage present with index2 61517
postalCode         44096
streetAddr           NaN
cityName      Willoughby
stateName             OH
Name: 61517, dtype: object
garbage present with index2 61609
postalCode        44054
streetAddr          NaN
cityName      Sheffield
stateName            OH
Name: 61609, dtype: object
garbage present with index2 62890
postalCode               44028
streetAddr                 NaN
cityName      Columbia Station
stateName                   OH
Name: 62890, dtype: object
garbage present with index2 63057
postalCode          85142
streetAddr            NaN
cityName      Queen Creek
stateName              AZ
Name: 63057, dtype: object
garbage present with index2 63297
postalCode       NaN
streetAddr       NaN
cityName      Weston
stateName         ON
Name: 63297, dtype: object
garbage present with index2 63341
postalCode         NaN
streetAddr         NaN
cityName      Paradise
stateName           NV
Name: 63341, dtype: object
garbage present with index2 64264
postalCode          44141
streetAddr            NaN
cityName      Brecksville
stateName              OH
Name: 64264, dtype: object
garbage present with index2 65996
postalCode               44039
streetAddr                 NaN
cityName      North Ridgeville
stateName                   OH
Name: 65996, dtype: object
garbage present with index2 66543
postalCode           NaN
streetAddr           NaN
cityName      Sacramento
stateName             CA
Name: 66543, dtype: object
garbage present with index2 66874
postalCode        85048
streetAddr          NaN
cityName      Ahwatukee
stateName            AZ
Name: 66874, dtype: object
garbage present with index2 66877
postalCode            85252
streetAddr              NaN
cityName      Metro Phoenix
stateName                AZ
Name: 66877, dtype: object
garbage present with index2 66958
postalCode       06897
streetAddr         NaN
cityName      Glendale
stateName           CT
Name: 66958, dtype: object
garbage present with index2 67996
postalCode     44255
streetAddr       NaN
cityName      Mantua
stateName         OH
Name: 67996, dtype: object

garbage present with index2 68985
postalCode                44118
streetAddr                  NaN
cityName      Cleveland Heights
stateName                    OH
Name: 68985, dtype: object
garbage present with index2 71048
postalCode       44095
streetAddr         NaN
cityName      Eastlake
stateName           OH
Name: 71048, dtype: object
garbage present with index2 71269
postalCode        15212
streetAddr          NaN
cityName      Pittsburg
stateName            PA
Name: 71269, dtype: object
garbage present with index2 71461
postalCode    07083
streetAddr      NaN
cityName      Union
stateName        NJ
Name: 71461, dtype: object
garbage present with index2 71941
postalCode          44026
streetAddr            NaN
cityName      Chesterland
stateName              OH
Name: 71941, dtype: object
garbage present with index2 73059
postalCode             44118
streetAddr               NaN
cityName      Shaker Heights
stateName                 OH
Name: 73059, dtype: object
garbage present with index2 73635
postalCode                  15129
streetAddr                    NaN
cityName      South Park Township
stateName                      PA
Name: 73635, dtype: object
garbage present with index2 73884
postalCode           61873
streetAddr             NaN
cityName      Saint Joseph
stateName               IL
Name: 73884, dtype: object
garbage present with index2 74856
postalCode          29707
streetAddr            NaN
cityName      Indian Land
stateName              SC
Name: 74856, dtype: object
garbage present with index2 74913
postalCode    H8N 0E3
streetAddr        NaN
cityName      LaSalle
stateName          QC
Name: 74913, dtype: object
garbage present with index2 78191
postalCode      61866
streetAddr        NaN
cityName      Rantoul
stateName          IL
Name: 78191, dtype: object
garbage present with index2 79375
postalCode     44321
streetAddr       NaN
cityName      Copley
stateName         OH
Name: 79375, dtype: object
garbage present with index2 79836
postalCode     H4P 1Y7
streetAddr         NaN
cityName      Montreal
stateName           QC
Name: 79836, dtype: object
garbage present with index2 80745
postalCode        89103
streetAddr          NaN
cityName      Las vegas
stateName            NV
Name: 80745, dtype: object
garbage present with index2 81377
postalCode        15120
streetAddr          NaN
cityName      Homestead
stateName            PA
Name: 81377, dtype: object
garbage present with index2 81510
postalCode          15317
streetAddr            NaN
cityName      South Hills
stateName              PA
Name: 81510, dtype: object
garbage present with index2 82471
postalCode       29708
streetAddr         NaN
cityName      Tega Cay
stateName           SC
Name: 82471, dtype: object
garbage present with index2 84645
postalCode                15106
streetAddr                  NaN
cityName      Robinson Township
stateName                    PA
Name: 84645, dtype: object
garbage present with index2 85050
postalCode               44138
streetAddr                 NaN
cityName      Olmsted Township
stateName                   OH
Name: 85050, dtype: object
garbage present with index2 85290
postalCode     44021
streetAddr       NaN
cityName      Burton
stateName         OH
Name: 85290, dtype: object
garbage present with index2 85863
postalCode                85379
streetAddr                  NaN
cityName      Surprise Crossing
stateName                    AZ
Name: 85863, dtype: object
garbage present with index2 85869
postalCode       44094
streetAddr         NaN
cityName      Kirtland
stateName           OH
Name: 85869, dtype: object
garbage present with index2 86155
postalCode         85044
streetAddr           NaN
cityName      Ahwahtukee
stateName             AZ
Name: 86155, dtype: object
garbage present with index2 86988
postalCode      15139
streetAddr        NaN
cityName      Oakmont
stateName          PA
Name: 86988, dtype: object
garbage present with index2 87042
postalCode     78701
streetAddr       NaN
cityName      Austin
stateName         TX
Name: 87042, dtype: object
garbage present with index2 87233
postalCode            15136
streetAddr              NaN
cityName      Mc Kees Rocks
stateName                PA
Name: 87233, dtype: object
garbage present with index2 87707
postalCode               NaN
streetAddr               NaN
cityName      Phoenix Valley
stateName                 AZ
Name: 87707, dtype: object
garbage present with index2 88030
postalCode          44077
streetAddr            NaN
cityName      Painesville
stateName              OH
Name: 88030, dtype: object
garbage present with index2 88038
postalCode           15101
streetAddr             NaN
cityName      Allison Park
stateName               PA
Name: 88038, dtype: object
garbage present with index2 88277
postalCode            44115
streetAddr              NaN
cityName      Cleveland, OH
stateName                OH
Name: 88277, dtype: object
garbage present with index2 88569
postalCode     NaN
streetAddr     NaN
cityName      Ajax
stateName       ON
Name: 88569, dtype: object
garbage present with index2 88803
postalCode       28056
streetAddr         NaN
cityName      Gastonia
stateName           NC
Name: 88803, dtype: object
garbage present with index2 88848
postalCode     44123
streetAddr       NaN
cityName      Euclid
stateName         OH
Name: 88848, dtype: object
garbage present with index2 89579
postalCode        NaN
streetAddr        NaN
cityName      Central
stateName          AZ
Name: 89579, dtype: object
garbage present with index2 90135
postalCode           44121
streetAddr             NaN
cityName      South Euclid
stateName               OH
Name: 90135, dtype: object
garbage present with index2 90218
postalCode      L3T 2G9
streetAddr          NaN
cityName      Thornhill
stateName            ON
Name: 90218, dtype: object
garbage present with index2 91584
postalCode    44139
streetAddr      NaN
cityName      Solon
stateName        OH
Name: 91584, dtype: object
garbage present with index2 91766
postalCode       15025
streetAddr         NaN
cityName      Clairton
stateName           PA
Name: 91766, dtype: object
garbage present with index2 93548
postalCode                   85260
streetAddr                     NaN
cityName      Westworld Scottsdale
stateName                       AZ
Name: 93548, dtype: object
garbage present with index2 93868
postalCode          44280
streetAddr            NaN
cityName      Valley City
stateName              OH
Name: 93868, dtype: object
garbage present with index2 94371
postalCode    61874
streetAddr      NaN
cityName      Savoy
stateName        IL
Name: 94371, dtype: object
garbage present with index2 95407
postalCode       15044
streetAddr         NaN
cityName      Gibsonia
stateName           PA
Name: 95407, dtype: object
garbage present with index2 96593
postalCode     44053
streetAddr       NaN
cityName      Lorain
stateName         OH
Name: 96593, dtype: object
garbage present with index2 97438
postalCode          15102
streetAddr            NaN
cityName      Bethel Park
stateName              PA
Name: 97438, dtype: object
garbage present with index2 97566
postalCode       15057
streetAddr         NaN
cityName      McDonald
stateName           PA
Name: 97566, dtype: object
garbage present with index2 99421
postalCode      44146
streetAddr        NaN
cityName      Bedford
stateName          OH
Name: 99421, dtype: object
garbage present with index2 99433
postalCode       M1L 4R9
streetAddr           NaN
cityName      North York
stateName             ON
Name: 99433, dtype: object
garbage present with index2 102949
postalCode       85377
streetAddr         NaN
cityName      Carefree
stateName           AZ
Name: 102949, dtype: object
garbage present with index2 103987
postalCode        89109
streetAddr          NaN
cityName      Las Vegas
stateName            CA
Name: 103987, dtype: object
garbage present with index2 105171
postalCode       85026
streetAddr         NaN
cityName      Phoenix
stateName           AZ
Name: 105171, dtype: object
garbage present with index2 105767
postalCode      15090
streetAddr        NaN
cityName      Wexford
stateName          PA
Name: 105767, dtype: object
garbage present with index2 108533
postalCode         44090
streetAddr           NaN
cityName      Wellington
stateName             OH
Name: 108533, dtype: object
garbage present with index2 109144
postalCode                  NaN
streetAddr                  NaN
cityName      Northwest Calgary
stateName                    AB
Name: 109144, dtype: object
garbage present with index2 110130
postalCode       NaN
streetAddr       NaN
cityName      Milton
stateName         ON
Name: 110130, dtype: object
garbage present with index2 110633
postalCode         NaN
streetAddr         NaN
cityName      Oakville
stateName           ON
Name: 110633, dtype: object
garbage present with index2 110667
postalCode     44060
streetAddr       NaN
cityName      Mentor
stateName         OH
Name: 110667, dtype: object

garbage present with index2 113373
postalCode         89128
streetAddr           NaN
cityName      Las Vegass
stateName             NV
Name: 113373, dtype: object
garbage present with index2 114081
postalCode      M8V 3E5
streetAddr          NaN
cityName      etobicoke
stateName            ON
Name: 114081, dtype: object
garbage present with index2 115474
postalCode       15116
streetAddr         NaN
cityName      Glenshaw
stateName           PA
Name: 115474, dtype: object
garbage present with index2 115612
postalCode                  NaN
streetAddr                  NaN
cityName      Broadview Heights
stateName                    OH
Name: 115612, dtype: object
garbage present with index2 117325
postalCode           44131
streetAddr             NaN
cityName      Independence
stateName               OH
Name: 117325, dtype: object
garbage present with index2 117784
postalCode                 16066
streetAddr                   NaN
cityName      Cranberry Township
stateName                     PA
Name: 117784, dtype: object
garbage present with index2 118236
postalCode    H7R 6B6
streetAddr        NaN
cityName        Laval
stateName          QC
Name: 118236, dtype: object
garbage present with index2 118936
postalCode           15136
streetAddr             NaN
cityName      Mckees Rocks
stateName               PA
Name: 118936, dtype: object
garbage present with index2 120673
postalCode    BL8 4DR
streetAddr        NaN
cityName         Bury
stateName         XGM
Name: 120673, dtype: object
garbage present with index2 120863
postalCode            85260
streetAddr              NaN
cityName      The Promenade
stateName                AZ
Name: 120863, dtype: object
garbage present with index2 120988
postalCode            NaN
streetAddr            NaN
cityName      East Credit
stateName              ON
Name: 120988, dtype: object
garbage present with index2 122040
postalCode          44040
streetAddr            NaN
cityName      Gates Mills
stateName              OH
Name: 122040, dtype: object
garbage present with index2 122264
postalCode          44202
streetAddr            NaN
cityName      Streetsboro
stateName              OH
Name: 122264, dtype: object
garbage present with index2 122713
postalCode      M8Z 4B6
streetAddr          NaN
cityName      Etobicoke
stateName            ON
Name: 122713, dtype: object
garbage present with index2 123649
postalCode         89191
streetAddr           NaN
cityName      Nellis AFB
stateName             NV
Name: 123649, dtype: object
garbage present with index2 126434
postalCode        15143
streetAddr          NaN
cityName      Sewickley
stateName            PA
Name: 126434, dtype: object
garbage present with index2 126613
postalCode        29732
streetAddr          NaN
cityName      Rock Hill
stateName            SC
Name: 126613, dtype: object
garbage present with index2 129690
postalCode       28035
streetAddr         NaN
cityName      Davidson
stateName           NC
Name: 129690, dtype: object
garbage present with index2 133846
postalCode             15068
streetAddr               NaN
cityName      New Kensington
stateName                 PA
Name: 133846, dtype: object
garbage present with index2 133954
postalCode           92703
streetAddr             NaN
cityName      Las Vegas Nv
stateName               CA
Name: 133954, dtype: object
garbage present with index2 134525
postalCode          28115
streetAddr            NaN
cityName      Mooresville
stateName              NC
Name: 134525, dtype: object
garbage present with index2 134654
postalCode           28079
streetAddr             NaN
cityName      Indian Trail
stateName               OH
Name: 134654, dtype: object
garbage present with index2 136572
postalCode         28075
streetAddr           NaN
cityName      Harrisburg
stateName             NC
Name: 136572, dtype: object
garbage present with index2 137484
postalCode               89183
streetAddr                 NaN
cityName      Las Vegas Valley
stateName                   NV
Name: 137484, dtype: object
garbage present with index2 139173
postalCode    L7E 3V9
streetAddr        NaN
cityName       Bolton
stateName          ON
Name: 139173, dtype: object
garbage present with index2 139568
postalCode             89011
streetAddr               NaN
cityName      Lake Las Vegas
stateName                 NV
Name: 139568, dtype: object
garbage present with index2 140588
postalCode          15017
streetAddr            NaN
cityName      Bridgeville
stateName              PA
Name: 140588, dtype: object
garbage present with index2 141040
postalCode        44124
streetAddr          NaN
cityName      Lyndhurst
stateName            OH
Name: 141040, dtype: object
garbage present with index2 141976
postalCode       85226
streetAddr         NaN
cityName      Chandler
stateName           CA
Name: 141976, dtype: object
garbage present with index2 142876
postalCode                    89139
streetAddr                      NaN
cityName      Las Vegas & Henderson
stateName                        NV
Name: 142876, dtype: object
garbage present with index2 143696
postalCode         28228
streetAddr           NaN
cityName      Charlotte
stateName             NC
Name: 143696, dtype: object
garbage present with index2 143751
postalCode          NaN
streetAddr          NaN
cityName      Pickering
stateName            ON
Name: 143751, dtype: object
garbage present with index2 143863
postalCode      28104
streetAddr        NaN
cityName      Mathews
stateName          NC
Name: 143863, dtype: object
garbage present with index2 144499
postalCode     T3A 2M4
streetAddr         NaN
cityName      Edgemont
stateName           AB
Name: 144499, dtype: object
garbage present with index2 145295
postalCode     28173
streetAddr       NaN
cityName      Marvin
stateName         NC
Name: 145295, dtype: object
garbage present with index2 146525
postalCode         29710
streetAddr           NaN
cityName      Lake Wylie
stateName             SC
Name: 146525, dtype: object
garbage present with index2 149757
postalCode           15136
streetAddr             NaN
cityName      McKees Rocks
stateName               PA
Name: 149757, dtype: object
garbage present with index2 151134
postalCode          NaN
streetAddr          NaN
cityName      Lake Mead
stateName            NV
Name: 151134, dtype: object
garbage present with index2 151443
postalCode    M6S 4N5
streetAddr        NaN
cityName         York
stateName          ON
Name: 151443, dtype: object
garbage present with index2 151578
postalCode           89004
streetAddr             NaN
cityName      Blue Diamond
stateName               NV
Name: 151578, dtype: object
garbage present with index2 151745
postalCode        15220
streetAddr          NaN
cityName      Allegheny
stateName            PA
Name: 151745, dtype: object
garbage present with index2 152625
postalCode         85331
streetAddr           NaN
cityName      cave creek
stateName             AZ
Name: 152625, dtype: object
garbage present with index2 153023
postalCode         28104
streetAddr           NaN
cityName      Weddington
stateName             NC
Name: 153023, dtype: object
garbage present with index2 153514
postalCode               T1Y
streetAddr               NaN
cityName      Division No. 6
stateName                 AB
Name: 153514, dtype: object
garbage present with index2 153520
postalCode    85207
streetAddr      NaN
cityName       mesa
stateName        AZ
Name: 153520, dtype: object
garbage present with index2 154014
postalCode    61864
streetAddr      NaN
cityName      Philo
stateName        IL
Name: 154014, dtype: object
garbage present with index2 156393
postalCode      28107
streetAddr        NaN
cityName      Midland
stateName          NC
Name: 156393, dtype: object
garbage present with index2 156819
postalCode               44105
streetAddr                 NaN
cityName      Cuyahoga Heights
stateName                   OH
Name: 156819, dtype: object
garbage present with index2 157731
postalCode                       NaN
streetAddr                       NaN
cityName      Whitchurch-Stouffville
stateName                         ON
Name: 157731, dtype: object
garbage present with index2 158155
postalCode        44264
streetAddr          NaN
cityName      Peninsula
stateName            CA
Name: 158155, dtype: object
garbage present with index2 159196
postalCode            44147
streetAddr              NaN
cityName      Broadview Hts
stateName                OH
Name: 159196, dtype: object

garbage present with index2 160444
postalCode       15202
streetAddr         NaN
cityName      Bellevue
stateName           PA
Name: 160444, dtype: object
garbage present with index2 161750
postalCode      85295
streetAddr        NaN
cityName      GIlbert
stateName          AZ
Name: 161750, dtype: object
garbage present with index2 161751
postalCode        44087
streetAddr          NaN
cityName      Twinsburg
stateName            OH
Name: 161751, dtype: object
garbage present with index2 162832
postalCode       L6G 0B9
streetAddr           NaN
cityName      Unionville
stateName             ON
Name: 162832, dtype: object
garbage present with index2 164809
postalCode          53572
streetAddr            NaN
cityName      Mount Horeb
stateName              WI
Name: 164809, dtype: object
garbage present with index2 165197
postalCode    44210
streetAddr      NaN
cityName       Bath
stateName        OH
Name: 165197, dtype: object
garbage present with index2 172814
postalCode        M5V
streetAddr        NaN
cityName      toronto
stateName          ON
Name: 172814, dtype: object
garbage present with index2 173765
postalCode     T1X 0L3
streetAddr         NaN
cityName      Beltline
stateName           AB
Name: 173765, dtype: object
garbage present with index2 176913
postalCode         89101
streetAddr           NaN
cityName      Las  Vegas
stateName             NV
Name: 176913, dtype: object
garbage present with index2 180517
postalCode         89141
streetAddr           NaN
cityName      Enterprise
stateName             NV
Name: 180517, dtype: object
garbage present with index2 180785
postalCode        48374
streetAddr          NaN
cityName      Los Vegas
stateName            NV
Name: 180785, dtype: object
garbage present with index2 183073
postalCode        85208
streetAddr          NaN
cityName      East Mesa
stateName            AZ
Name: 183073, dtype: object
garbage present with index2 183163
postalCode         53558
streetAddr           NaN
cityName      Mc Farland
stateName             WI
Name: 183163, dtype: object
garbage present with index2 183995
postalCode        89002
streetAddr          NaN
cityName      HENDERSON
stateName            NV
Name: 183995, dtype: object
garbage present with index2 185049
postalCode                    H3A 2G4
streetAddr                        NaN
cityName      Quartier des Spectacles
stateName                          QC
Name: 185049, dtype: object
garbage present with index2 186114
postalCode      98112
streetAddr        NaN
cityName      Seattle
stateName          WI
Name: 186114, dtype: object
garbage present with index2 186306
postalCode             85326
streetAddr               NaN
cityName      Rainbow Valley
stateName                 AZ
Name: 186306, dtype: object
garbage present with index2 186366
postalCode      15071
streetAddr        NaN
cityName      Oakdale
stateName          PA
Name: 186366, dtype: object
garbage present with index2 190135
postalCode    44234
streetAddr      NaN
cityName      Hiram
stateName        OH
Name: 190135, dtype: object
done

In [87]:
dfaddrAB = dfaddrAB.dropna()
dfaddrAB

,postalCode,streetAddr,cityName,stateName
0,85016,2818 E Camino Acequia Drive,Phoenix,AZ
1,L5R 3E7,30 Eglinton Avenue W,Mississauga,ON
2,T2R 1L3,"1210 8th Street SW, Unit 220",Calgary,AB
3,89149,"6955 N Durango Dr, Ste 1116",Las Vegas,NV
4,85281,4 E University Dr,Tempe,AZ
...,...,...,...,...
192603,85210,440 S Extension Rd,Mesa,AZ
192604,H3B 1A6,521 St. Catherine Street W,Montréal,QC
192605,M5B 1V8,244 Victoria Street,Toronto,ON
192606,85044,10210 South 50th Pl,Phoenix,AZ
192607,89113,"6670 S Tenaya Way, Ste 120, The Body Spa",Las Vegas,NV

In [88]:
dfaddrAB.to_csv('addressAB.csv', index=False)

In [89]:
dfcity = pd.DataFrame(df[['city', 'state']])
dfcity

               city state
0           Phoenix    AZ
1       Mississauga    ON
2           Calgary    AB
3         Las Vegas    NV
4             Tempe    AZ
...             ...   ...
192604     Montréal    QC
192605      Toronto    ON
192606      Phoenix    AZ
192607    Las Vegas    NV
192608       Peoria    AZ

[192609 rows x 2 columns]

In [90]:
dfcity.rename(columns={'city':'cityName', 'state':'stateName'}, inplace=True)
dfcity.drop_duplicates(keep ='first', inplace = True)
dfcity.to_csv('cityAB.csv', index=False)
dfcity

           cityName stateName
0           Phoenix        AZ
1       Mississauga        ON
2           Calgary        AB
3         Las Vegas        NV
4             Tempe        AZ
...             ...       ...
190907      Pahrump        NV
191280    ETOBICOKE        ON
191517  Rockey View        AB
191552   Pittsburch        PA
191855  Richmonhill        ON

[1257 rows x 2 columns]

In [91]:
##################################### dfcity table done ########################################
dfstate = pd.DataFrame(df['state'])
dfstate.drop_duplicates(keep ='first', inplace = True)
dfstate.rename(columns = {'state':'stateName'})
dfstate

       state
0         AZ
1         ON
2         AB
3         NV
5         NC
6         QC
15        OH
16        PA
18        WI
91        IL
340       SC
3461      NY
10763     GA
12704     TX
19506     CA
23996     AL
30532    DUR
36860    XWY
40400     TN
48744     FL
49561    XGM
66406     VA
66958     CT
71461     NJ
71562     WA
71985     AR
72114     UT
83036     NM
87945    XGL
98097    DOW
112327   BAS
113193    NE
117176    AK
146687   CON
151131    BC
174574    VT

In [92]:
dfstate.to_csv('stateAB.csv', index=False)